### PR TITLE
[glsl-in] support inverse function

### LINKED ISSUE #357: Semantic Error: Unknown function: inverse
Running naga with the vertex shader from tutorial 13 of Learn Wgpu errors with:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError { kind: SemanticError("Unknown function: inverse") }', examples/convert.rs:91:14
```

Here's the shader code:

```glsl
#version 450

layout(location=0) in vec3 a_position;
layout(location=1) in vec2 a_tex_coords;
layout(location=2) in vec3 a_normal;
layout(location=3) in vec3 a_tangent;
layout(location=4) in vec3 a_bitangent;

layout(location=0) out vec2 v_tex_coords;
layout(location=1) out vec3 v_position; // UPDATED!
layout(location=2) out vec3 v_light_position; // NEW!
layout(location=3) out vec3 v_view_position; // NEW!

layout(set=1, binding=0) 
uniform Uniforms {
    vec3 u_view_position; 
    mat4 u_view_proj;
};

layout(location=5) in mat4 model_matrix;

// NEW!
layout(set=2, binding=0) uniform Light {
    vec3 light_position;
    vec3 light_color;
};

void main() {
    v_tex_coords = a_tex_coords;

    mat3 normal_matrix = mat3(transpose(inverse(model_matrix)));
    vec3 normal = normalize(normal_matrix * a_normal);
    vec3 tangent = normalize(normal_matrix * a_tangent);
    vec3 bitangent = normalize(normal_matrix * a_bitangent);

    // UDPATED!
    mat3 tangent_matrix = transpose(mat3(
        tangent,
        bitangent,
        normal
    ));

    vec4 model_space = model_matrix * vec4(a_position, 1.0);
    v_position = model_space.xyz;

    // NEW!
    v_position = tangent_matrix * model_space.xyz;
    v_light_position = tangent_matrix * light_position;
    v_view_position = tangent_matrix * u_view_position;

    gl_Position = u_view_proj * model_space;
}
```

### PR DESCRIPTION
**Pull request by Systemcluster**
Add support for the `inverse` GLSL function.

I also added some other math functions to the GLSL frontend that were already available but were missing from the parsing step.

Resolves #357 

~~To make the code in #357 work, I had to add support for `TypeInner::Matrix` in the `Expression::As` branch in the typifier - I'm not sure if that's correct, feedback is welcome.~~

### CODE REVIEW

File: src/proc/typifier.rs [hunk 1]
```diff
@@ -457,6 +474,15 @@ impl Typifier {
                     size,
                     width,
                 } => Resolution::Value(crate::TypeInner::Vector { kind, size, width }),
+                crate::TypeInner::Matrix {
+                    columns,
+                    rows,
+                    width,
+                } => Resolution::Value(crate::TypeInner::Matrix {
```
Comment (kvark) [inline src/proc/typifier.rs:481]: does this actually work anywhere? I thought type casts are limited to vectors and scalars

**Review by kvark — COMMENTED** [review]
Looks great, just one tiny note to answer

File: src/proc/typifier.rs (hunk 1 above)
Comment (Systemcluster) [reply src/proc/typifier.rs:481]: You're right, this results in `OpBitcast` instructions for `OpTypeMatrix` which is invalid. I think I'll just take that change out of this PR and look for another way to make the shader in #357 parse properly later. Would that be alright?

Comment (kvark) [reply src/proc/typifier.rs]: That would be fine, yes.
Could you point me to where exactly #357 needs this cast?

**Review by kvark — APPROVED** [review]

File: src/proc/typifier.rs (hunk 1 above)
Comment (Systemcluster) [reply src/proc/typifier.rs]: If I interpret everything right it's in the line `mat3 normal_matrix = mat3(transpose(inverse(model_matrix)));` and seems to be at the `mat3(` or the assignment step.

The log output is as follows:

```
[2021-02-14T17:12:38Z DEBUG naga::proc::typifier] Resolving Handle(16) = AccessIndex { base: Handle(14), index: 1 } : Handle(Handle(1))
[2021-02-14T17:12:38Z DEBUG naga::proc::typifier] Resolving Handle(17) = Math { fun: Inverse, arg: Handle(13), arg1: None, arg2: None } : Value(Matrix { columns: Quad, rows: Quad, width: 4 })
[2021-02-14T17:12:38Z DEBUG naga::proc::typifier] Resolving Handle(18) = Math { fun: Transpose, arg: Handle(17), arg1: None, arg2: None } : Value(Matrix { columns: Quad, rows: Quad, width: 4 })
thread 'main' panicked at 'ParseError { kind: SemanticError("Can\'t resolve type: IncompatibleOperand { op: \"as\", operand: \"Matrix { columns: Quad, rows: Quad, width: 4 }\" }") }', examples\convert.rs:54:31
```

Comment (kvark) [reply src/proc/typifier.rs]: ah, so you are talking about extracting mat3 out of mat4. We don't have IR for this yet. We need to figure out how upstream WebGPU is going to do this.
You can always work around this though (in GLSL frontend, for example), by doing `mat3(matrix.x.xyz, matrix.y.xyz, matrix.z.xyz)`
