### PR TITLE
[glsl-out] Fix writing identifiers starting with gl_

### LINKED ISSUE #814: [glsl-out] Generated shader use identifiers starting with "gl_"
Found in https://github.com/gfx-rs/naga/issues/812

```bash
cat test.glsl.vert | glslangValidator --stdin -S vert
stdin
ERROR: 0:17: 'gl_VertexIndex' : identifiers starting with "gl_" are reserved 
```

### PR DESCRIPTION
**Pull request by Gordon-F**
Fix #814. One more fix for #812

### CODE REVIEW

File: src/back/glsl/mod.rs [hunk 1]
```diff
@@ -2122,6 +2117,17 @@ impl<'a, W: Write> Writer<'a, W> {
             uniforms,
         })
     }
+
+    /// Helper method used to produce GL specific unique name
+    /// GL identifiers starting with "gl_" are not allowed
+    fn get_name(&self, name_key: &NameKey) -> String {
```
Comment (kvark) [inline src/back/glsl/mod.rs:2123]: instead of handling it here, can we instead add support for "reserved prefixes" to `Namer` itself?

Comment (Gordon-F) [reply src/back/glsl/mod.rs]: Done!

**Review by kvark — APPROVED** [review]
