### PR TITLE
wgsl-in: Improve assignment diagnostics

### LINKED ISSUE #2052: Assignment to swizzle produces unhelpful error message
Given the program:

```
fn f() {
   var v = vec2(0);
   v.xy = vec2(1);
}
```

Naga complains:

```
error: the left-hand side of an assignment must be a reference
  ┌─ assign-to-swizzle.wgsl:2:20
  │  
2 │      var v = vec2(0);
  │ ╭───────────────────^
3 │ │    v.xy = vec2(1);
  │ ╰───────^ expression is not a reference

Could not parse WGSL
```

This leads to questions in chat like:

> Hi. What's the equivalent WGSL code to this?
> 
>     p.xy = f(p.xy)
> 
> I get this error and have no idea how to write this nicely...

The error message did not convey to the user that swizzle assignment is simply unsupported.

### PR DESCRIPTION
**Pull request by SparkyPotato**
This improves the diagnostics on invalid assignment statements.
Fixes #2052.

Given:
```wgsl
fn f() {
    var v = vec2(0);
    v.xy = vec2(1);
}
```
Naga used to error with:
```
error: the left-hand side of an assignment must be a reference
  ┌─ test.wgsl:3:5
  │
3 │     v.xy = vec2(1);
  │     ^^^^ expression is not a reference
```
Now:
```
error: invalid left-hand side of assignment
  ┌─ test.wgsl:3:5
  │
3 │     v.xy = vec2(1);
  │     ^^^^ cannot assign to this expression
  │
  = note: WGSL does not support assignments to swizzles
  = note: consider assigning each component individually
```

Given:
```wgsl
fn f() {
    3 + 5;
}
```
Naga used to error with:
```
error: the left-hand side of an assignment must be a reference
  ┌─ test.wgsl:2:5
  │
2 │     3 + 5;
  │     ^ expression is not a reference
```
Now:
```
error: expected assignment or increment/decrement, found '3 + 5'
  ┌─ test.wgsl:2:5
  │
2 │     3 + 5;
  │     ^^^^^ expected assignment or increment/decrement
```

Given:
```wgsl
fn f() {
    3 + 5 = 10;
}
```
Naga used to error with:
```
error: the left-hand side of an assignment must be a reference
  ┌─ test.wgsl:2:5
  │
2 │     3 + 5 = 10;
  │     ^ expression is not a reference
```
Now:
```
error: invalid left-hand side of assignment
  ┌─ test.wgsl:2:5
  │
2 │     3 + 5 = 10;
  │     ^^^^^ cannot assign to this expression
```

Given:
```
fn f() {
    let a = 10;
	a = 20;
}
```
Naga used to error with:
```
error: invalid left-hand side of assignment
  ┌─ test.wgsl:3:2
  │
3 │     a = 20;
  │     ^ cannot assign to this expression
```
Now:
```
error: invalid left-hand side of assignment
  ┌─ test.wgsl:3:2
  │
3 │     a = 20;
  │     ^ cannot assign to this expression
  │
  = note: 'a' is an immutable binding
  = note: consider declaring it with `var` instead of `let`
```

`Error` has breaking changes made to it.

### CODE REVIEW

**Comment by jimblandy** [comment]
@SparkyPotato This needs a rebase.

File: src/front/wgsl/mod.rs [hunk 1]
```diff
@@ -439,6 +452,14 @@ impl<'a> Error<'a> {
                 labels: vec![(span.clone(), "expression is not a reference".into())],
                 notes: vec![],
             },
+            Error::InvalidAssignment{ ref span, ty} => ParseError {
+                message: "invalid left-hand side of assignment".into(),
+                labels: vec![(span.clone(), "cannot assign to this expression".into())],
+                notes: match ty {
+                    InvalidAssignmentType::Swizzle => vec!["WGSL does not support assignments to swizzles".into(), "trying assigning each component individually".into()],
```
Comment (jimblandy) [inline src/front/wgsl/mod.rs]: "try assigning"

File: src/front/wgsl/mod.rs [hunk 2]
```diff
@@ -3342,13 +3346,19 @@ impl Parser {
...
-                ty: match context.expressions.get_mut(reference.handle) {
-                    crate::Expression::Swizzle { .. } => InvalidAssignmentType::Swizzle,
-                    _ => InvalidAssignmentType::Other,
+                ty: if context.named_expressions.contains_key(&reference.handle) {
+                    InvalidAssignmentType::ImmutableBinding
+                } else {
+                    match context.expressions.get_mut(reference.handle) {
+                        crate::Expression::Swizzle { .. } => InvalidAssignmentType::Swizzle,
+                        _ => InvalidAssignmentType::Other,
+                    }
```
Comment (jimblandy) [inline src/front/wgsl/mod.rs:3355]: Let's pull this out into a temporary variable, and not have big computations in the midst of the `Error::InvalidAssignment` construction.

File: src/front/wgsl/mod.rs [hunk 3]
```diff
@@ -439,6 +453,15 @@ impl<'a> Error<'a> {
                 labels: vec![(span.clone(), "expression is not a reference".into())],
                 notes: vec![],
             },
+            Error::InvalidAssignment{ ref span, ty} => ParseError {
+                message: "invalid left-hand side of assignment".into(),
+                labels: vec![(span.clone(), "cannot assign to this expression".into())],
+                notes: match ty {
+                    InvalidAssignmentType::Swizzle => vec!["WGSL does not support assignments to swizzles".into(), "consider assigning each component individually".into()],
```
Comment (jimblandy) [inline src/front/wgsl/mod.rs:460]: I'm surprised that `cargo fmt` doesn't wrap those long lines. The CI should have caught that, though, so maybe I'm missing something.

**Review by jimblandy — CHANGES_REQUESTED** [review]
Let's get the examples you put in the PR description into the test suite. It seems like they'd fit well in `tests/wgsl-errors.rs`, as a `check`-based test.

The simplification to `Error::Unexpected` is great. In the future, see if it's possible to separate out changes like that, that make a bunch of changes all over the place, into their own commits. This makes the series easier to review, because it makes it easier to see how simple the other changes are. But don't worry about that for this PR.

**Comment by jimblandy** [comment]
@SparkyPotato This looks fantastic, btw - thanks very much!

File: src/front/wgsl/mod.rs (hunk 1 above)
Comment (SparkyPotato) [reply src/front/wgsl/mod.rs]: I changed this to "consider assigning", would you prefer it to be "try assigning"?

Comment (jimblandy) [reply src/front/wgsl/mod.rs]: Nope, just wanted the "trying assigning" typo fixed. "consider" is fine too.

**Review by jimblandy — APPROVED** [review]
Looks good to me - thank you!

**Comment by jimblandy** [comment]
Okay, here's why `cargo fmt -- --check` wasn't complaining about the long lines in `front/wgsl/mod.rs`: https://github.com/rust-lang/rustfmt/issues/3863

I'll push a workaround for that.
