### PR TITLE
[wgsl-in] Allow sign() to take int argument

### LINKED ISSUE #2458: `sign()` incorrectly does not accept i32 arguments (WGSL)
I believe the issue is right here: 

https://github.com/gfx-rs/naga/blob/6aca2e2b5ec1ac634e3e06e9a7d6113290070234/src/valid/expression.rs#L979

Sign can accept i32s per the WGSL spec: https://www.w3.org/TR/WGSL/#sign-builtin

### PR DESCRIPTION
**Pull request by fornwall**
Fixes #2458.

The main work here is to make it work on metal, which does not have an `int` overload of `sign()`. So we introduce a `naga_isign` polyfill function there.

Currently the metal backend always emits the `naga_isign` polyfill. What is a good way to only do that if necessary? We need to declare the function before it's used, so we can't do it after writing out the functions. Is there some mechanism to visit all expressions without duplicating a lot of logic?

### CODE REVIEW

**Review by ErichDonGubler — COMMENTED** [review]
This mostly LGTM (noting that I don't have merge authority), minus nits and one question: would it be possible to omit this new polyfill unless needed? I'm not familiar with the matter, but I know we've thought about lazily emitting supporting polyfills WRT constructing array members of HLSL structures before.

☝🏻I think @jimblandy or @teoxoy would know the answer to this.

File: src/back/msl/writer.rs [hunk 1]
```diff
@@ -34,6 +34,7 @@ const RAY_QUERY_FUN_MAP_INTERSECTION: &str = "_map_intersection_type";
 
 pub(crate) const MODF_FUNCTION: &str = "naga_modf";
 pub(crate) const FREXP_FUNCTION: &str = "naga_frexp";
+pub(crate) const NAGA_ISIGN_FUNCTION: &str = "naga_isign";
```
Comment (ErichDonGubler) [inline src/back/msl/writer.rs:37]: nitpick: It would be more consistent with surrounding code to omit the `NAGA_*` prefix here:

```suggestion
pub(crate) const ISIGN_FUNCTION: &str = "naga_isign";
```

File: src/back/msl/writer.rs [hunk 2]
```diff
@@ -4103,6 +4116,17 @@ impl<W: Write> Writer<W> {
         Ok(info)
     }
 
+    fn write_polyfills(&mut self) -> Result<(), Error> {
+        writeln!(self.out)?;
+        writeln!(
```
Comment (ErichDonGubler) [inline src/back/msl/writer.rs:4121]: thought(non-blocking): It'd be nice to avoid two writes and roll the implicit `'\n'` into the next call. I'm not sure what other chunks of the codebase do off the top of my head, though.

File: src/valid/expression.rs [hunk 3]
```diff
@@ -992,6 +991,22 @@ impl super::Validator {
                             _ => return Err(ExpressionError::InvalidArgumentType(fun, 0, arg)),
                         }
                     }
+                    Mf::Sign => {
+                        if arg1_ty.is_some() | arg2_ty.is_some() | arg3_ty.is_some() {
```
Comment (ErichDonGubler) [inline src/valid/expression.rs:995]: question(blocking): Is there a reason we're using the bit-or operation (`|`) instead of the short-circuiting version (`||`)?

```suggestion
                        if arg1_ty.is_some() || arg2_ty.is_some() || arg3_ty.is_some() {
```

**Review by ErichDonGubler — COMMENTED** [review]
This mostly LGTM (noting that I don't have merge authority), minus nits and one question: ~~would it be possible to omit this new polyfill unless needed? I'm not familiar with the matter, but I know we've thought about lazily emitting supporting polyfills WRT constructing array members of HLSL structures before.~~ EDIT: 😅 I see that you're also asking this question in the OP:

> Currently the metal backend always emits the naga_isign polyfill. What is a good way to only do that if necessary? We need to declare the function before it's used, so we can't do it after writing out the functions. Is there some mechanism to visit all expressions without duplicating a lot of logic?

☝🏻I think @jimblandy or @teoxoy would know the answer to this.

File: src/back/msl/writer.rs (hunk 1 above)
Comment (fornwall) [reply src/back/msl/writer.rs]: Indeed, thanks!

File: src/valid/expression.rs (hunk 3 above)
Comment (fornwall) [reply src/valid/expression.rs]: Thanks! There was no reason, created https://github.com/gfx-rs/naga/pull/2465 to fix this in other existing places in the same file.

File: src/back/msl/writer.rs (hunk 2 above)
Comment (fornwall) [reply src/back/msl/writer.rs]: Thanks! While it doesn't seem to be the existing practice, I've done the change to avoid the extra call now - let me know if I should revert that.

File: src/back/msl/writer.rs [hunk 4]
```diff
@@ -1713,7 +1715,17 @@ impl<W: Write> Writer<W> {
                     Mf::Reflect => "reflect",
                     Mf::Refract => "refract",
                     // computational
-                    Mf::Sign => "sign",
+                    Mf::Sign => match arg_type {
```
Comment (jimblandy) [inline src/back/msl/writer.rs:1718]: You should use `arg_type.scalar_kind()` here.

**Review by jimblandy — CHANGES_REQUESTED** [review]
Rather than generating a definition for a polyfill, consider simply emitting the code inline. See the way the Metal backend handles `MathFunction::Dot` for an example:

- It calls `back::msl::Writer::put_dot_product` to emit the expression at the point of use.
- In `back::msl::Writer::update_expressions_to_bake`, we ensure that the operand is placed in a temporary variable first, so that we don't evaluate the argument expression more than once.

File: src/back/msl/writer.rs (hunk 4 above)
Comment (fornwall) [reply src/back/msl/writer.rs]: Thanks! Done in d16e605aa6f58043cef24b6cb8204bcf0dfb3cab

File: tests/in/math-functions.wgsl [hunk 5]
```diff
@@ -8,6 +8,7 @@ fn main() {
     let d = radians(v);
     let e = saturate(v);
     let g = refract(v, v, f);
+    let h = sign(-1);
```
[the remark this answers is not in the document]
Comment (fornwall) [reply tests/in/math-functions.wgsl]: Done in f6a2a918d48176cf255fd52b2ed85686950b07c3

**Comment by fornwall** [comment]
> Rather than generating a definition for a polyfill, consider simply emitting the code inline. 

Thanks for the pointers @jimblandy! Changed to emitting inline in 32e96a560a39f8a90b18e8daa28d7ff7fc480d5e.

**Review by jimblandy — APPROVED** [review]
Thank you very much!
