### PR TITLE
[wgsl-in] Implement module-level scoping

### LINKED ISSUE #2072: [wgsl-in] allow functions to be declared literally after entry point
This is discovered in Deno when using tensorflow.js with its WebGPU backend, when tfjs declares a function `fn main` after the entry point `fn _start`. The generated WGSL works in Chrome Canary 108.0.5329.0 (V8 10.8.79) but fails in Deno, error details at https://github.com/tensorflow/tfjs/issues/6842#issuecomment-1262708937.

Experiments in https://github.com/tensorflow/tfjs/issues/6842#issuecomment-1263196772 showed that in naga, invoked functions have to be declared literally before the entry point and the `@compute` directive.

The current WGSL specification (20220922) seems to have [function scoping](https://www.w3.org/TR/2022/WD-WGSL-20220922/#function-declaration-sec), replacing the [lexical scoping](https://github.com/gpuweb/gpuweb/issues/559) back in 2020.

> A function declaration [must](https://www.w3.org/TR/2022/WD-WGSL-20220922/#shader-creation-error) only occur at [module scope](https://www.w3.org/TR/2022/WD-WGSL-20220922/#module-scope). A function name is [in scope](https://www.w3.org/TR/2022/WD-WGSL-20220922/#in-scope) for the entire program.

Given the generated script [shader.wgsl](https://github.com/gfx-rs/naga/files/9682291/shader.wgsl.txt), should the function `main` be available in scope when `_start` is invoked?

### PR DESCRIPTION
**Pull request by SparkyPotato**
Try 2 :)

- fixes https://github.com/gfx-rs/naga/issues/1745
- fixes https://github.com/gfx-rs/naga/issues/1044
- fixes https://github.com/gfx-rs/naga/issues/2076
- fixes https://github.com/gfx-rs/naga/issues/2071
- fixes https://github.com/gfx-rs/naga/issues/2105
- fixes https://github.com/gfx-rs/naga/issues/1775
- fixes https://github.com/gfx-rs/naga/issues/2089
- fixes https://github.com/gfx-rs/naga/issues/1996

This PR separates parsing from lowering, by generating an AST, which desugars as much as possible down to something like Naga IR. 

The AST is then used to resolve identifiers while lowering to Naga IR.

### CODE REVIEW

**Comment by SparkyPotato** [comment]
@jimblandy Would be great if you could a look at the AST definition!

Also, you were talking about how 2 passes would be all that was necessary.
However, lowering to Naga IR requires that the dependencies of each module-level declaration are known beforehand, as we need to (reverse) topologically sort the declaration list so that all dependencies are processed before their dependents.

The only way I can think of doing this in two passes is to maintain a set of the raw identifiers referenced by each declaration during parsing, and then using those to sort the declarations, but I'm not quite sure if this will actually be faster than resolving on the same IR, and then sorting.

**Comment by jimblandy** [comment]
Here's how I was thinking it could work (I haven't actually tried this yet):

1) For the first pass, we parse mostly as we do now, except that identifiers in expressions, types, statements, etc. are represented by placeholders that just store the name. Except for the placeholders, we try to produce something as close to the `crate` IR as possible immediately. 

    The placeholders mean that we will have types that look very much like `crate::Expression`, etc. except that certain variants that assume knowledge of definitions (`LocalVariable`, obviously, but also things like `AccessIndex`, since we don't know struct type definitions) hold identifiers instead of handles. Some cases will need to change in more profound ways; for example, we can't tell whether `S(x)` is a `Call` or a `Compose` until we know the definition of `S`. But as much as possible, the unresolved types should resemble the `crate` types, so that people familiar with the rest of Naga can make assumptions.

2) For the resolution pass, starting with the entry points, start building true `crate::{Function, EntryPoint, Type, ...}` values. When we hit a placeholder, check to see if we already have a previously-resolved definition for that name. If so, use it. Otherwise, immediately recurse on resolving that name (which adds the resulting fully-resolved definition to the `Module` under construction), and then resume processing the placeholder, whose definition we now know. When we're done, add our completed definition to the `Module`.

This amounts to a depth-first traversal of the DAG of definitions, where we "mark nodes as visited" by adding resolved definitions to the `Module`. This ensures that definitions appear in the `Module` in dependency order, in the process of replacing placeholders with `Handle`s.

After we've processed the entry points, we may want to just walk the top-level unresolved definitions and finish off anything unvisited. Such definitions could be safely dropped from the module, since they're unreachable from any entry point (and we should probably produce warnings about this), but it's very useful for testing to have everything in the input appear in the `Module`. Maybe this step would be optional.

Naturally, we will need to check for cyclic references at the point of recursion.

As I say, I haven't tried this, so there may be aspects of the problem I've missed - but it seems like something along these lines ought to be possible somehow.

**Comment by jimblandy** [comment]
You should use `Arena`, `UniqueArena`, and `Handle` for the unresolved representation. That is one of the tricks Naga uses for performance: broadly speaking, caches and prefetchers are much happier with arrays than heap allocation, especially if you can phrase some computation as an iteration over the array.

Otherwise, try to make the change as undisruptive and limited as you can while still preserving legibility.

**Comment by SparkyPotato** [comment]
Recursion was something I thought of, but processing each declaration does use quite a large amount of stack, so we might end up stack overflowing quite quick, especially on Windows, where the default stack size is 2 MB.

We can probably use [stacker](https://github.com/rust-lang/stacker), which is what rustc uses.

About the warnings, I do plan to add error recovery to the frontend so we can output more than one error, and will add warnings for unused items there (I did have this implemented in my other frontend, it isn't too big of a change).

**Comment by jimblandy** [comment]
Using arenas instead of trees for expressions should reduce the stack depth, though. And with a little care we could avoid recursing on statements at all - I think only `Call` and `Atomic` need resolution. So the depth would only be determined by the number of references we're in the midst of resolving, and not so much by the interior structure of the functions themselves.

**Comment by jimblandy** [comment]
`stacker` sounds 1) amazing and 2) wildly unsafe and definitely not something we want to ship in a browser. So that's one easy solution out the window. I think stack depth is a legitimate concern here.

**Comment by SparkyPotato** [comment]
I think keeping a set of (textual) dependencies used by each declaration during parsing, and then using that to post-order depth-first sort would be the easiest solution, and it shouldn't really impact performance too much.

The post-order sorting with cycle detection does require recursion, however it should require much less stack space than resolving the function.

I have also implemented parsing and finalized the AST structures, would be great if you could take a look, and tell me if any changes are needed :)

**Comment by SparkyPotato** [comment]
I did have to keep track of locals during the initial parse phase, to fix an issue with code like this:
```rs
fn a() {
    let a = b();
}

fn b() -> i32 {
    let a = 20;
    return a;
}
```
If we just kept a set of textual dependencies, `fn a` being shadowed by `let a` would create a cyclic dependency error.

**Comment by i509VCB** [comment]
I'm curious if the ast generated here is publicly accessible. I do have a case where I need to look at the shader's ast to figure out how to setup bind groups

**Comment by SparkyPotato** [comment]
> I'm curious if the ast generated here is publicly accessible. I do have a case where I need to look at the shader's ast to figure out how to setup bind groups

It's not public at the moment, but I can make it so.

However, can you not just use the `Module` that the front end produces instead? It will probably have more information than the semi-AST IR used here.

**Comment by SparkyPotato** [comment]
@jimblandy This has reached feature parity with the existing frontend, and passes all the functionality-based tests. The diagnostics snapshots don't pass yet, but fixing those shouldn't change too much. You can start reviewing now.

Surprisingly, performance has actually *improved*. The current frontend consistently takes around 3.6 ms for the `front/wgsl` benchmark, while this does it in around 2.9 ms (a 20% decrease).

The only difference in output is that I don't initialize `LocalVariable`s with constants since I'm not too sure if that added complexity is actually worth it. I can add it back if it's something wanted, though.

**Comment by SparkyPotato** [comment]
@teoxoy I've moved as much as I think possible back (parsing + errors).

`construction.rs` hasn't been moved because I have made quite a few changes to it, and it also needs to be in the `lower` module for privacy reasons.

Do tell me if there's anything else I need to do to make reviewing easier!

**Comment by teoxoy** [comment]
Thanks for reducing the diff, but it still looks like quite a lot of changes which will make browsing the history of the files challenging.

Let's move the code in `lower/mod.rs` to `mod.rs` and `lower/construction.rs` to `construction.rs` (with existing code where it previously was).

After this, the changes should be reviewable and after the review we can see how to proceed with new files/folders (and moving code around).

**Comment by SparkyPotato** [comment]
Got it down to +4495 -2811, not sure if anything more is possible.

File: src/lib.rs [hunk 1]
```diff
@@ -573,8 +573,7 @@ pub struct Type {
 }
 
 /// Enum with additional information, depending on the kind of type.
-#[derive(Debug, Eq, Hash, PartialEq)]
-#[cfg_attr(feature = "clone", derive(Clone))]
+#[derive(Debug, Clone, Eq, Hash, PartialEq)]
```
Comment (teoxoy) [inline src/lib.rs:576]: I think we can get by without having `TypeInner` implement `Clone`.

It looks like this was only needed because of `ConcreteConstructor`.

**Review by teoxoy — CHANGES_REQUESTED** [review]
Thanks for reducing the diff!
I took a brief look around the code and left a few comments.

**General comment**
Only user defined structs should have a `crate::Type.name` (some of the backends now generate extra type aliases for built-in types).

File: tests/wgsl-errors.rs [hunk 2]
```diff
@@ -64,12 +64,12 @@ fn invalid_integer() {
...
-        r###"error: expected ';', found '.'
-  ┌─ wgsl:1:21
+        "const scale: f32 = 1.1.;",
+        r###"error: expected identifier, found ';'
+  ┌─ wgsl:1:24
   │
-1 │ let scale: f32 = 1.1.;
-  │                     ^ expected ';'
+1 │ const scale: f32 = 1.1.;
+  │                        ^ expected identifier
```
[the remark this answers is not in the document]
Comment (SparkyPotato) [reply tests/wgsl-errors.rs:72]: Not sure anything can be done about this.

The previous parser parsed only a single literal or construction, but we now parse a full expression because it is valid in the spec (we don't actually support most expressions, but we should) - so this becomes a field access on `1.1`.

File: src/front/wgsl/construction.rs [hunk 3]
```diff
@@ -1,679 +1,609 @@
...
-        width: Bytes,
-    },
+use crate::front::wgsl;
+use crate::front::wgsl::ast;
+use crate::front::wgsl::ast::{ArraySize, ConstructorType};
+use crate::front::wgsl::Error;
+use crate::front::wgsl::{ExpressionContext, Lowerer, OutputContext};
+use crate::{Handle, Span};
+
+enum ConcreteConstructor {
```
[the remark this answers is not in the document]
Comment (SparkyPotato) [reply src/front/wgsl/construction.rs:8]: That would lead to #2105, so we do have to fully resolve the type.

File: benches/criterion.rs [hunk 4]
```diff
@@ -42,12 +42,11 @@ fn frontends(c: &mut Criterion) {
     #[cfg(all(feature = "wgsl-in", feature = "serialize", feature = "deserialize"))]
     group.bench_function("bin", |b| {
         let inputs_wgsl = gather_inputs("tests/in", "wgsl");
-        let mut parser = naga::front::wgsl::Parser::new();
         let inputs_bin = inputs_wgsl
             .iter()
             .map(|input| {
                 let string = std::str::from_utf8(input).unwrap();
-                let module = parser.parse(string).unwrap();
+                let module = naga::front::wgsl::parse_str(string).unwrap();
```
[the remark this answers is not in the document]
Comment (SparkyPotato) [reply benches/criterion.rs:49]: `parse_str` does both parsing and lowering. Do you want me to split each benchmark into just parsing, and both parsing and lowering?

**Comment by SparkyPotato** [comment]
> Only user defined structs should have a crate::Type.name (some of the backends now generate extra type aliases for built-in types).

Wouldn't this lead to worse validation errors, where something like `Vec { kind: Float, width: 4 }` would be used instead of just `vec4<f32>`?

File: tests/in/lexical-scopes.wgsl [hunk 5]
```diff
@@ -29,9 +29,7 @@ fn loopLexicalScope(a: bool) {
 
 fn forLexicalScope(a: f32) {
     let a = false;
-    for (var a = 0; a < 1; a++) {
-        let a = 3.0;
-    }
+    for (var a = 0; a < 1; a++) {}
```
[the remark this answers is not in the document]
Comment (teoxoy) [reply tests/in/lexical-scopes.wgsl:32]: In the section about the [For Statement](https://gpuweb.github.io/gpuweb/wgsl/#for-statement) they say:

image

There is also an example in that section showing the additional scope around the loop (if you were to translate it to a loop).

File: tests/wgsl-errors.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (teoxoy) [reply tests/wgsl-errors.rs:72]: ah, I see - it's fine then

File: benches/criterion.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (teoxoy) [reply benches/criterion.rs:49]: Got tripped up by the lowering missing in the `front/wgsl` bench.

Considering the `Parser` was reused in the benchmarks before, can we try to reuse the `Parser` and maybe the `Index` as well? We might see some additional benefits when it comes to perf from doing so.

[the remark this answers is not in the document]
Comment (SparkyPotato) [reply benches/criterion.rs:49]: `Parser` and `Index` each just have a single `Vec` (`Index` also preallocates it with the required capacity), so I'm not sure that's worth the added complexity.

**Comment by SparkyPotato** [comment]
> I think for errors we can have a method that gives us the proper name. Also, considering we have other front-ends that don't use the same syntax (i.e. `vec4<f32>`) for types, we should avoid passing those through IR.

Done!

**Comment by teoxoy** [comment]
Thanks! There seem to be a few more places where we still set the name:
- 5 in `Lowerer.construct`
- 1 in `ExpressionContext.resolve_type`

File: src/lib.rs (hunk 1 above)
Comment (SparkyPotato) [reply src/lib.rs:576]: `ExpressionContext::resolve_type` also does require cloning, and I'm not sure how I can get around that.

Comment (teoxoy) [reply src/lib.rs:576]: `TypeResolution` has a `Clone` impl. See how it's used here: https://github.com/gfx-rs/naga/blob/1650581fe7a94ed40067313f3cd205414dd4febf/src/front/glsl/types.rs#L296

Consider adding a `Typifier.get_handle` fn; could be used by both frontends.

File: src/front/wgsl/mod.rs [hunk 6]
```diff
@@ -169,53 +182,75 @@ pub enum Error<'a> {
...
+        expected: Range<u32>,
+        found: u32,
+    },
+    FunctionReturnsVoid(Span),
     Other,
 }
 
 impl<'a> Error<'a> {
-    fn as_parse_error(&self, source: &'a str) -> ParseError {
+    pub fn as_parse_error(&self, source: &'a str) -> ParseError {
```
Comment (teoxoy) [inline src/front/wgsl/mod.rs:207]: Let's keep this private

File: src/front/wgsl/mod.rs [hunk 7]
```diff
@@ -4723,28 +3796,2227 @@ impl Parser {
         }
     }
 
-    pub fn parse(&mut self, source: &str) -> Result<crate::Module, ParseError> {
+    pub fn parse<'a>(&mut self, source: &'a str) -> Result<TranslationUnit<'a>, ParseError> {
```
Comment (teoxoy) [inline src/front/wgsl/mod.rs:3797]: Let's keep the fn signature the same considering this is part of our public API and there isn't much people can do with a `TranslationUnit<'a>`.

This means we don't have to expose `Lowerer` and we can undo the changes to `parse_str` & the benchmark file.

**Comment by SparkyPotato** [comment]
@teoxoy I have done a few things:
1. Add `Typifier::get_handle` and used that in `ExpressionContext`.
2. Moved `ensure_type_exists` to `OutputContext`, and used that everywhere.
3. Created a sort of workaround for two-stage borrows to avoid the need to clone `TypeInner` - this does lead to code duplication, so let me know if you can think of a better solution.

**Comment by teoxoy** [comment]
> 1. Added `Typifier::get_handle` and used that in `ExpressionContext`. The GLSL frontend has not been edited.

Feel free to change the GLSL frontend as well.

> 2. Moved `ensure_type_exists` to `OutputContext`, and used that everywhere.

We can make use of `ensure_type_exists` in a few more places:
- 2 in `ExpressionContext.create_zero_value_constant`
- 1 in `Lowerer.construct`

> 3. Created a sort of workaround for two-stage borrows to avoid the need to clone `TypeInner` - this does lead to code duplication, so let me know if you can think of a better solution.

Can't think of doing it any other way right now since we match on those `TypeInner`s but will keep it in mind.

Thanks for the updates!

**Comment by teoxoy** [comment]
> The only difference in output is that I don't initialize `LocalVariable`s with constants since I'm not too sure if that added complexity is actually worth it. I can add it back if it's something wanted, though.

_from https://github.com/gfx-rs/naga/pull/2075#issuecomment-1304453265_

I also noticed this by looking at the test snapshots. I think it should be fine for now considering we'll have to deal with const expressions differently soon.

**Comment by SparkyPotato** [comment]
All changes done.

**Comment by teoxoy** [comment]
I'll do one last round of review tomorrow and take a look at all those issues as well.
Will probably edit the top comment so that they will all get automatically closed.

Considering the size and scope of the PR, we have a lot to go through.
Thanks for being so receptive!

**Comment by SparkyPotato** [comment]
Great! Thanks for taking the time to review!

**Comment by teoxoy** [comment]
Considering we are fixing #2105 with this PR, it would be great to add some tests for type aliases.

**Comment by SparkyPotato** [comment]
> Considering we are fixing #2105 with this PR, it would be great to add some tests for type aliases.

Is there any specific place I should add them? Or should I create a new snapshot test file?

**Comment by teoxoy** [comment]
A new snapshot test file would be best. Thanks!

File: src/front/wgsl/construction.rs [hunk 8]
```diff
@@ -1,679 +1,635 @@
...
+    }
+
+    pub(super) fn const_construct(
+        &mut self,
+        span: Span,
+        constructor: &ConstructorType<'source>,
+        components: &[Handle<ast::Expression<'source>>],
+        mut ctx: OutputContext<'source, '_, '_>,
+    ) -> Result<crate::ConstantInner, Error<'source>> {
+        // TODO: Support zero values, splatting and inference.
```
Comment (teoxoy) [inline src/front/wgsl/construction.rs:552]: What does this refer to?

**Comment by teoxoy** [comment]
There were too many conversions between `Span` (`Range<usize>`) and `NagaSpan`. i.e. `Span.into()`/`NagaSpan.to_range().unwrap()`.

And even previsouly when I worked on the WGSL frontend, the `Span`(`Range<usize>`)/`NagaSpan` duality only got in the way.

I removed `Span`(`Range<usize>`) completely and the code is much nicer to work on now. (no more unnecessary `.clone()` calls either because ranges don't implement `Clone`).

File: src/front/wgsl/construction.rs (hunk 8 above)
Comment (SparkyPotato) [reply src/front/wgsl/construction.rs:544]: That would be #1956 and #1957.

File: src/front/wgsl/ast.rs [hunk 9]
```diff
@@ -0,0 +1,344 @@
...
+
+#[derive(Debug)]
+pub struct Statement<'a> {
+    pub kind: StatementKind<'a>,
+    pub span: Span,
+}
+
+#[derive(Debug)]
+pub enum StatementKind<'a> {
+    VarDecl(Box<VarDecl<'a>>),
```
Comment (teoxoy) [inline src/front/wgsl/ast.rs:195]: I think this box can be removed.

File: src/front/wgsl/ast.rs [hunk 10]
```diff
@@ -0,0 +1,344 @@
...
+    Image {
+        dim: crate::ImageDimension,
+        arrayed: bool,
+        class: crate::ImageClass,
+    },
+    Sampler {
+        comparison: bool,
+    },
+    BindingArray {
+        base: Box<Type<'a>>,
```
Comment (teoxoy) [inline src/front/wgsl/ast.rs:176]: I think we can replace the 3 boxes in `TypeKind` with `Handle`s (and an additional `Arena`).

File: src/front/wgsl/ast.rs (hunk 9 above)
Comment (teoxoy) [reply src/front/wgsl/ast.rs:195]: Also, let's rename the variant and type to `LocalDecl` (similar to our `GlobalDecl`).

Comment (SparkyPotato) [reply src/front/wgsl/ast.rs:195]: Without that, the size of a statement is severely bloated.

Performance doesn't really change anyways, even with our relatively declaration-heavy tests.

File: src/front/wgsl/ast.rs (hunk 10 above)
Comment (SparkyPotato) [reply src/front/wgsl/ast.rs:176]: I'm not sure this is worth it either, as type nesting is rare, and is also usually quite shallow.

File: src/front/wgsl/ast.rs (hunk 9 above)
Comment (teoxoy) [reply src/front/wgsl/ast.rs:195]: Hmm, 56 vs 80.

But if we put `ast::Type` in an `Arena` and share `Handle`s in the AST, it gets us back down to 56.

Comment (SparkyPotato) [reply src/front/wgsl/ast.rs:195]: I still think that pessimising the 'normal' path (non-nested types) to arena pushes won't be worth it compared to the relatively rare nested types and local declaration.

Though, as is usual with most micro-optimizations like this, I really doubt it's gonna make any difference that isn't just normal benchmark noise.

File: src/front/wgsl/ast.rs (hunk 10 above)
Comment (teoxoy) [reply src/front/wgsl/ast.rs:170]: I agree that most types won't be nested but we are dealing with user input here, so we need to expect the worst scenario where we'll have a bunch of `Box`es spread out in memory.

File: src/front/wgsl/ast.rs (hunk 9 above)
Comment (teoxoy) [reply src/front/wgsl/ast.rs]: I tried this change locally and got 2-3% better perf (compared with this branch).
It's not groundbreaking but it allows us to still be performant with arbitrary nesting while also keeping things consistent.

Comment (jimblandy) [reply src/front/wgsl/ast.rs]: Arenas are the way to go here.

**Comment by SparkyPotato** [comment]
Looks great!

I also think we should use something like `aho_corasick` or `daachorse` for the reserved identifier detection since we'll go to `O(ident_length)` instead of `O(reserved_list_length)`.

**Comment by teoxoy** [comment]
> I also think we should use something like `aho_corasick` or `daachorse` for the reserved identifier detection since we'll go to `O(ident_length)` instead of `O(reserved_list_length)`.

That's a good idea!

The speed of `daachorse` compared with `aho_corasick` looks substantial (according to the benchmarks `daachorse` has in their readme) but we could check out both and see which one is faster for us. 
Let's experiment with this in a separate PR though (this change should be quite self-contained).

**Comment by SparkyPotato** [comment]
Is most of the reviewing done? Can we start looking at separating things again, because `wgsl/mod.rs` is a gargantuan mess, to say the least?

I was thinking of a few things:
- Rename the main `Parser` to `Frontend`, which caches the lexer, parser, and lowerer (A small API change). 
- Move each pass into its own individual module, as I had done.

**Comment by teoxoy** [comment]
> Is most of the reviewing done? 

I still need to take a look at some things but on my side mostly yes.
@jimblandy just started to take a look.

> I was thinking of a few things:
> - Rename the main `Parser` to `Frontend`, which caches the lexer, parser, and lowerer (A small API change). 
> - Move each pass into its own individual module, as I had done.

Looking at the diff, most of the `Lowerer` code looks new (at least to git) and I think we can move it in a `lowerer.rs` file but let's keep the `Parser` in `mod.rs` since the diff for it is more or less accurate. If we want to move other things around, we can do so after this PR lands since we'll squash it and git won't recognize the file moves.

Regarding the `Parser` name, let's keep it as it is for now (at least in our public API) since we use the same terminology for the other frontends. If we want to change it in our public API, I'd say we do it for all frontends which might as well be a separate change.

**Comment by SparkyPotato** [comment]
If we're going to move things around later, might as well move everything into different files in a later PR, and the same for the `Frontend` rename.

**Comment by SparkyPotato** [comment]
Is there anything left to do?

**Review by teoxoy — APPROVED** [review]
From my side this is good to go. There are still some small things that can be improved but I think we can do that in following PRs.

Solid work!

**Comment by jimblandy** [comment]
I'm getting the following errors when I try `make validate-spv`:

```
Validating spv/access.spvasm
error: line 145: Structure id 12 decorated as Block for variable in Uniform storage class must follow standard uniform buffer layout rules: member 0 is a matrix with stride 8 not satisfying alignment to 16
  %Baz = OpTypeStruct %mat3v2float

make: *** [Makefile:34: validate-spv] Error 1
```

The CI doesn't seem upset, though - am I doing something wrong?

**Comment by jimblandy** [comment]
It seems like CI is using `focal/universe amd64 spirv-tools amd64 2020.1-2`, and I'm using `SPIRV-Tools v2022.4-dev v2022.2-85-ga98f05d0`.

File: src/span.rs [hunk 11]
```diff
@@ -85,6 +93,15 @@ impl From<Range<usize>> for Span {
     }
 }
 
+impl std::ops::Index<Span> for str {
```
Comment (jimblandy) [inline src/span.rs:96]: sweet

File: src/front/wgsl/mod.rs [hunk 12]
```diff
@@ -30,10 +29,9 @@ use codespan_reporting::{
         termcolor::{ColorChoice, NoColor, StandardStream},
     },
 };
-use std::{borrow::Cow, convert::TryFrom, ops};
+use std::{borrow::Cow, convert::TryFrom, ops::Range};
 use thiserror::Error;
 
-type Span = ops::Range<usize>;
```
Comment (jimblandy) [inline src/front/wgsl/mod.rs:36]: very nice

File: src/front/wgsl/mod.rs [hunk 13]
```diff
@@ -328,241 +334,291 @@ impl<'a> Error<'a> {
...
+                            ),
+                        ]
+                    })
+                    .collect(),
+                notes: vec![],
+            },
+            Error::ConstExprUnsupported(span) => ParseError {
+                message: "this constant expression is not supported".to_string(),
+                labels: vec![(span, "expression is not supported".into())],
+                notes: vec!["this should be fixed in a future version of Naga".into()],
```
Comment (jimblandy) [inline src/front/wgsl/mod.rs:588]: Let's link to an issue here. (If we don't have an issue, let's file one.)

File: src/front/wgsl/mod.rs [hunk 14]
```diff
@@ -328,241 +334,291 @@ impl<'a> Error<'a> {
...
+                    }
+                    .into(),
+                )],
+                notes: vec![if uint {
+                    format!("suffix the integer with a `u`: '{}u'", &source[span])
+                } else {
+                    let span = span.to_range().unwrap();
+                    format!(
+                        "remove the `u` suffix: '{}'",
+                        &source[span.start..span.end - 1]
```
Comment (jimblandy) [inline src/front/wgsl/mod.rs:607]: There's no way this could end up falling in the midst of a multibyte UTF-8 character, right?

File: src/front/wgsl/index.rs [hunk 15]
```diff
@@ -0,0 +1,143 @@
...
+
+    pub fn visit_ordered(&self) -> impl Iterator<Item = Handle<ast::GlobalDecl<'a>>> + '_ {
+        self.dependency_order.iter().copied()
+    }
+}
+
+pub struct ResolvedDependency<'a> {
+    pub decl: Handle<ast::GlobalDecl<'a>>,
+    pub usage: Span,
+}
```
Comment (jimblandy) [inline src/front/wgsl/index.rs]: It seems like this doesn't need to be `pub`.

```suggestion
struct ResolvedDependency<'a> {
    decl: Handle<ast::GlobalDecl<'a>>,
    usage: Span,
}
```

File: src/front/wgsl/index.rs [hunk 16]
```diff
@@ -0,0 +1,143 @@
...
+    module: &'temp ast::TranslationUnit<'source>,
+    visited: Vec<bool>,
+    temp_visited: Vec<bool>,
+    path: Vec<ResolvedDependency<'source>>,
+    out: Vec<Handle<ast::GlobalDecl<'source>>>,
+}
+
+impl<'a> DependencySolver<'a, '_> {
+    fn solve(mut self) -> Result<Vec<Handle<ast::GlobalDecl<'a>>>, Error<'a>> {
+        for id in self.module.decls.iter().map(|x| x.0) {
```
Comment (jimblandy) [inline src/front/wgsl/index.rs:97]: The way Naga generally does this is clearer, I think:

```suggestion
        for (id, _decl) in self.module.decls.iter() {
```

File: src/front/wgsl/index.rs [hunk 17]
```diff
@@ -0,0 +1,143 @@
...
+                            usage: dep.usage,
+                        })
+                    } else {
+                        let start_at = self
+                            .path
+                            .iter()
+                            .rev()
+                            .enumerate()
+                            .find(|&(_, dep)| dep.decl == dep_id)
+                            .map(|x| x.0)
```
Comment (jimblandy) [inline src/front/wgsl/index.rs:145]:
```suggestion
                            .find_map(|(i, dep)| (dep.decl == dep_id).then_some(i))
```

**Review by jimblandy — COMMENTED** [review]
Okay, I've finally got some time to start looking at this. I pushed a bunch of comments and docs I wrote in the process of reading; if you could give that a look and make sure I haven't really misunderstood something, that'd be great.

Some initial comments:

**Comment by jimblandy** [comment]
I have more time blocked out for reviewing this tomorrow.

File: src/front/wgsl/index.rs [hunk 18]
```diff
@@ -0,0 +1,143 @@
...
+
+        self.temp_visited[id_usize] = false;
+        self.visited[id_usize] = true;
+        self.out.push(id);
+
+        Ok(())
+    }
+}
+
+const fn decl_ident<'a>(decl: &ast::GlobalDecl<'a>) -> ast::Ident<'a> {
```
[the remark this answers is not in the document]
Comment (SparkyPotato) [reply src/front/wgsl/index.rs:185]: It would, but that wouldn't work when we implement `static_assert`.

File: src/front/wgsl/mod.rs (hunk 14 above)
Comment (SparkyPotato) [reply src/front/wgsl/mod.rs:607]: Yeah the last character is always guaranteed to be a `u`.

**Comment by SparkyPotato** [comment]
> I pushed a bunch of comments and docs I wrote in the process of reading; if you could give that a look and make sure I haven't really misunderstood something, that'd be great.

I made a slight change to the docs on `Error::Redefinition`, since it's used also for the redefinition of locals.

**Comment by jimblandy** [comment]
This program doesn't seem to work:

```
fn f() -> i32 {
   return g(1);
}

fn g(i: i32) -> i32 {
   return i;
}
```

I get the following output:

```
error: no definition in scope for identifier: 'g'
  ┌─ new.wgsl:2:11
  │
2 │    return g(1);
  │           ^ unknown identifier
```

**Comment by jimblandy** [comment]
The `ast::Expression::Call` case needs to record the reference in `ctx.unresolved`, the way `parse_function_statement` does.

File: src/front/wgsl/mod.rs [hunk 19]
```diff
@@ -1559,1180 +1697,348 @@ impl Parser {
...
+                    to,
+                    ty_span: span,
                 }
-                crate::ConstantInner::Composite {
-                    ty: composite_ty,
-                    components,
+            }
+            // everything else must be handled later, since they can be hidden by user-defined functions.
+            _ => {
+                let arguments = self.parse_arguments(lexer, ctx.reborrow())?;
```
Comment (jimblandy) [inline src/front/wgsl/mod.rs:1873]: This needs to record a dependency as well (and there should be a test for this):

```suggestion
                ctx.unresolved.insert(ast::Dependency {
                    ident: name,
                    usage: name_span,
                });

                let arguments = self.parse_arguments(lexer, ctx.reborrow())?;
```

**Review by jimblandy — COMMENTED** [review]
Some more comments:

File: src/front/wgsl/mod.rs [hunk 20]
```diff
@@ -3302,1438 +2532,2807 @@ impl Parser {
...
+        lexer: &mut Lexer<'a>,
+        mut ctx: ParseExpressionContext<'a, '_, '_>,
+    ) -> Result<Handle<ast::Type<'a>>, Error<'a>> {
+        self.push_rule_span(Rule::TypeDecl, lexer);
+
+        let (name, span) = lexer.next_ident_with_span()?;
+
+        let ty = match self.parse_type_decl_impl(lexer, name, ctx.reborrow())? {
+            Some(ty) => ty,
+            None => ast::Type::User(ast::Ident { name, span }),
```
Comment (jimblandy) [inline src/front/wgsl/mod.rs:2635]: Another missing dependancy:

```suggestion
            None => {
                ctx.unresolved.insert(ast::Dependency {
                    ident: name,
                    usage: span,
                });
                ast::Type::User(ast::Ident { name, span })
            },
```

**Review by jimblandy — COMMENTED** [review]
I think we need a bunch of new tests for forward references.

**Comment by SparkyPotato** [comment]
Fixed most of the issues, and added a test (`module-scope.wgsl`) for all global declarations. Do tell me if I've missed anything.

**Comment by jimblandy** [comment]
We don't support this yet:

```
type MyF32 = f32;
type MyVecF32 = vec3<MyF32>;
```

This gives an error:

```
error: unknown scalar type: 'MyF32'
  ┌─ new.wgsl:2:22
  │
2 │ type MyVecF32 = vec3<MyF32>;
  │                      ^^^^^ unknown scalar type
  │
  = note: Valid scalar types are f32, f64, i32, u32, bool
```

The spec says that the type parameter to `vec3` is a `type_specifier`, not `type_specifier_without_ident`.

Given that this is going to need to support forward references too, I think this is going to take some pretty big changes to `ast::Type`. The old code didn't support it either, so should we leave this for another PR?

**Comment by SparkyPotato** [comment]
I'd say leaving it for a later PR would be a better idea.

File: src/front/wgsl/mod.rs [hunk 21]
```diff
@@ -3980,760 +3002,2339 @@ impl Parser {
...
-        }
+        Ok(ctx.ensure_type_exists(inner))
     }
 
-    pub fn parse(&mut self, source: &str) -> Result<crate::Module, ParseError> {
-        self.reset();
+    fn constant(
+        &mut self,
+        expr: Handle<ast::Expression<'source>>,
+        arena: &Arena<ast::Expression<'source>>,
```
Comment (jimblandy) [inline src/front/wgsl/mod.rs:5241]: Taking the arena explicitly here, while also taking the `OutputContext`, is delicate, and I think there's a bug. When I compile the following program:

```
fn f() -> i32 {
   let a = array<i32,u32(42)>(64);
   return a[13];
}
```

I end up with an array whose size is 64, not 42:

- The `ast::ConstructorType::Array` case of `Lowerer::constructor` carefully passes `ctx.global_expressions` as the `arena` argument to `self.constant`, so that the array's size is looked up in the global expression arena, as it should, yielding the `Construct` expression for `u32(42)`. This is all fine.
- But then the `ast::Expression::Construct` case of `Lowerer::constant_inner` simply calls `const_construct`, which doesn't let you specify any arena. Since the `OutputContext` does have a `read_expressions` arena, we switch back to the function's expression arena.
- Now the operand of that `u32` construction expression is looked up in the wrong arena, yielding `64` instead of `42`.

As a result, we end up with a malformed `Module`:

```
Module {
    types: {
        [1]: Type {
            name: None,
            inner: Scalar {
                kind: Sint,
                width: 4,
            },
        },
        [2]: Type {
            name: None,
            inner: Scalar {
                kind: Uint,
                width: 4,
            },
        },
        [3]: Type {
            name: None,
            inner: Array {
                base: [1],
                size: Constant(
                    [2],
                ),
                stride: 4,
            },
        },
    },
    constants: {
        [1]: Constant {
            name: None,
            specialization: None,
            inner: Scalar {
                width: 4,
                value: Sint(
                    64,
                ),
            },
        },
        [2]: Constant {
            name: None,
            specialization: None,
            inner: Composite {
                ty: [2],
                components: [
                    [1],
                ],
            },
        },
        [3]: Constant {
            name: None,
            specialization: None,
            inner: Scalar {
                width: 4,
                value: Sint(
                    13,
                ),
            },
        },
    },
    ...
```

There's a second bug, in that the construction expression isn't evaluated by the front end, but the arena-crossing leaves us with `u32(64)` instead of `u32(42)`.

We could fix this by introducing something like `global_expr_as_expr` on `OutputContext`, and then dropping the `arena` argument, so that the entire array expression is interpreted using the proper context. But I wonder if there isn't some not-to-horrible way to catch these kinds of bugs at compile time.

**Review by jimblandy — CHANGES_REQUESTED** [review]
A bug, and a few more comments:

**Comment by jimblandy** [comment]
I pushed another batch of documentation. If you could give them a quick look, that'd be great.

I think I'm almost done with the review. It's holidays here, but I can pick this up on Monday and try to finish it off.

File: src/front/wgsl/mod.rs (hunk 21 above)
Comment (teoxoy) [reply src/front/wgsl/mod.rs:5355]: I remember seeing this kind of behavior while working on `const-expressions` (on top of this PR). IIRC I fixed it by always making sure the array length goes in/comes from `global_expressions`.

I was thinking at the time that it might be nice to know from which arena the handle is from (by tagging the arena and its handles with a phantom type or some id); then we could panic if we try to index an arena with a handle from a different arena. Actually thinking about this now, we could achieve the same thing by using a tuple  with the ast expression type and a marker type (`Global` and `Local`) for each of the 2 expression arenas.

Or just putting all the ast expressions of all functions in one big arena in the module and avoid the confusion altogether.

Comment (SparkyPotato) [reply src/front/wgsl/mod.rs:5355]: I fixed this by just giving `const_construct` the arena as well.

File: src/front/wgsl/mod.rs [hunk 22]
```diff
@@ -3980,760 +3002,2339 @@ impl Parser {
...
-                if let Some(explicit_ty) = given_ty {
-                    let con = &module.constants[const_handle];
-                    let type_match = match con.inner {
-                        crate::ConstantInner::Scalar { width, value } => {
-                            module.types[explicit_ty].inner
-                                == crate::TypeInner::Scalar {
-                                    kind: value.scalar_kind(),
-                                    width,
-                                }
+    fn resolve_ast_type(
```
[the remark this answers is not in the document]
Comment (SparkyPotato) [reply src/front/wgsl/mod.rs:5262]: I renamed everything to just what they works on, removing the `parse_` and `lower_` prefixes.

File: src/front/wgsl/mod.rs (hunk 21 above)
Comment (SparkyPotato) [reply src/front/wgsl/mod.rs:5323]: > Or just putting all the ast expressions of all functions in one big arena in the module and avoid the confusion altogether.

This seems like a great idea. 😛

**Comment by SparkyPotato** [comment]
The docs look great!

File: src/front/wgsl/mod.rs (hunk 21 above)
Comment (jimblandy) [reply src/front/wgsl/mod.rs:5323]: Just one big arena sounds cool to me. Are there any downsides?

**Comment by jimblandy** [comment]
I have a patch ready that merges the expression arenas. It seems to work fine.

File: src/front/mod.rs [hunk 23]
```diff
@@ -89,6 +89,19 @@ impl Typifier {
         self.resolutions[expr_handle.index()].inner_with(types)
     }
 
+    pub fn get_handle(
+        &self,
+        expr_handle: Handle<crate::Expression>,
+        types: &mut UniqueArena<crate::Type>,
+    ) -> Handle<crate::Type> {
```
Comment (jimblandy) [inline src/front/mod.rs:96]: Rather than doing this, I think we should use `TypeResolution` more places in `front::wgsl`, and just lean on the `ensure_type_exists` methods to convert those into `Handle` values when we really need to. Working on a patch for this now.

**Comment by jimblandy** [comment]
Hmm. This drops the name:

```
type T = i32;
let y: T = 1;
```

**Comment by SparkyPotato** [comment]
> Hmm. This drops the name from the type:
> 
> ```
> type T = i32;
> const y: T = 1;
> ```

Yeah, we discard type aliases as soon as they are resolved. Using type alias names when possible is quite hard, even rustc doesn't do it.

Solutions to fixing that include:
- Duplicating the type with a different name. This would require `TypeInner: Clone`, however.
- Creating a `TypeInner::Alias` variant. This would work but I don't think type aliases should be a part of the IR.

**Comment by jimblandy** [comment]
@teoxoy Could you give [040b700](https://github.com/gfx-rs/naga/pull/2075/commits/040b70083aed43bed2d593b1107846a895500593) a review?

**Review by teoxoy — APPROVED** [review]

**Comment by teoxoy** [comment]
LGTM, I think this should be ready to merge now.

**Review by jimblandy — APPROVED** [review]
All right, let's go.

**Comment by vicary** [comment]
Thanks for the hard work guys!

When would be the next release date with this included? I really want to see this land in `wgpu` and Deno!

**Comment by jimblandy** [comment]
@cwfitzgerald is planning the next release. Connor?

**Comment by cwfitzgerald** [comment]
25th of this month!

**Comment by vicary** [comment]
@cwfitzgerald That's exciting, thanks!
