### PR TITLE
glsl-in: Allow multiple array specifiers

### LINKED ISSUE #1769: [glsl-in] 2D array support
This shader:

```glsl
#version 460 core

shared float h[2][2];

void main() {}
```

produces this error:
```
error: Expected Comma or Semicolon, found LeftBracket
  ┌─ shader.comp:3:18
  │
3 │ shared float h[2][2];
  │                  ^
```

### PR DESCRIPTION
**Pull request by JCapucho**
Closes #1769

### CODE REVIEW

File: src/front/glsl/parser/types.rs [hunk 1]
```diff
@@ -10,45 +10,76 @@ use crate::{
...
                     },
                 },
-                span,
+                *span,
             );
-            let end_meta = self.expect(parser, TokenValue::RightBracket)?.meta;
-            meta.subsume(end_meta);
-            Ok(Some((ArraySize::Constant(constant), meta)))
+
+            Ok(true)
```
Comment (kvark) [inline src/front/glsl/parser/types.rs:72]: I don't understand why we are mutating `ty` and returning `Ok(bool)` if we could instead return something like `Result<Option<Handle<Type>>>`. Do you think this would be a feasible thing to change here?

Comment (JCapucho) [reply src/front/glsl/parser/types.rs:72]: We definitely could but I don't what the benefit would be since we would be mutating the type anyways.

Comment (kvark) [reply src/front/glsl/parser/types.rs:72]: Where would we be mutating the type? This would just return a new type.
Or do you mean that the caller would likely reassign the type anyway? That's OK, I think.

Comment (JCapucho) [reply src/front/glsl/parser/types.rs:72]: Yes the caller always reassigns the type

Comment (kvark) [reply src/front/glsl/parser/types.rs:72]: I think that would still be a better internal API.
