### PR TITLE
[glsl-out] Add stage postfix to generated global name

### LINKED ISSUE #1615: Shader translation error for wgpu shadow/water examples with GLES backend
Since wgpu commit ["Remove block decorations"](https://github.com/gfx-rs/wgpu/commit/39606585296a3c20214fc60818e210f3b4a541de ), running

`wgpu$ RUST_LOG=WARN WGPU_BACKEND=gles cargo run --example water`

gives

```
[2021-12-19T15:14:10Z WARN  wgpu::backend::direct] Shader translation error for stage VERTEX | FRAGMENT | VERTEX_FRAGMENT: error: declarations for uniform `_group_0_binding_0` are inside blocks `Uniforms_block_0Vertex` and `Uniforms_block_0Fragment`
[2021-12-19T15:14:10Z WARN  wgpu::backend::direct] Please report it to https://github.com/gfx-rs/naga
```

Similarly for the "shadow" example. Last tested with wgpu commit 54f20b / naga 0.8.

Platform:
Arch Linux with mesa 21.3.1-12
`Using Mesa Intel(R) UHD Graphics (TGL GT2) (Gl)`

### PR DESCRIPTION
**Pull request by Gordon-F**
Fix #1615

### CODE REVIEW

File: src/front/wgsl/lexer.rs [hunk 1]
```diff
@@ -9,7 +9,7 @@ fn _consume_str<'a>(input: &'a str, what: &str) -> Option<&'a str> {
 }
 
 fn consume_any(input: &str, what: impl Fn(char) -> bool) -> (&str, &str) {
-    let pos = input.find(|c| !what(c)).unwrap_or_else(|| input.len());
+    let pos = input.find(|c| !what(c)).unwrap_or(input.len());
```
Comment (kvark) [inline src/front/wgsl/lexer.rs:12]: I think clippy yells at this because `len()` is a function call that could be conditional/avoided

File: src/front/wgsl/lexer.rs [hunk 2]
```diff
@@ -261,7 +261,7 @@ fn consume_number(input: &str) -> (Token, &str) {
 
     let pos = working_substr
         .find(|c| !what(c))
-        .unwrap_or_else(|| working_substr.len());
+        .unwrap_or(working_substr.len());
```
Comment (kvark) [inline src/front/wgsl/lexer.rs:264]: Same. Also, unrelated to the PR.

**Review by kvark — CHANGES_REQUESTED** [review]
Thank you for this fix!
A few small things.

File: src/back/glsl/mod.rs [hunk 3]
```diff
@@ -305,6 +305,16 @@ impl fmt::Display for VaryingName<'_> {
     }
 }
 
+impl ShaderStage {
+    fn to_str(self) -> &'static str {
+        match self {
+            ShaderStage::Compute => "cs",
```
Comment (kvark) [inline src/back/glsl/mod.rs:311]: nit: you can use `Self::` here

**Review by kvark — APPROVED** [review]
Thank you!

**Comment by kvark** [comment]
published in 0.8.1
