### PR TITLE
[msl-out]: Properly write default values for non-scalar types.

### LINKED ISSUE #1585: Metal incorrect bounds checking on the shadow shader
Blocking `wgpu` update right now:
```
Caused by:
    In Device::create_render_pipeline
      note: label = `main`
    Internal error in VERTEX shader: Metal: program_source:138:83: error: incompatible operand types ('const constant Light' and 'int')
        Light light = metal::uint(_e21) < 1 + (_buffer_sizes.size2 - 0 - 96) / 96 ? s_lights.data[_e21] : 0;
                                                                                  ^ ~~~~~~~~~~~~~~~~~~~   ~
program_source:185:48: error: incompatible operand types ('const constant Light' and 'int')
        Light light_1 = metal::uint(_e21) < 10 ? u_lights.data.inner[_e21] : 0;
                                               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~   ~


', wgpu/src/backend/direct.rs:2233:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'shadow' panicked at 'UNEXPECTED TEST FAILURE', wgpu/examples/shadow/../../tests/common/mod.rs:269:9
```

Shader - https://github.com/gfx-rs/wgpu/blob/3b48ed28f37d41aaac53ce76501cd801bc41bdc1/wgpu/examples/shadow/shader.wgsl

### PR DESCRIPTION
**Pull request by jimblandy**
Fixes #1585.

Commits should be individually CI-clean.

### CODE REVIEW

**Comment by kvark** [comment]
As discussed on the matrix, let's investigate if it's possible to simplify the zero/default initialization without as much code complication. For example, https://godbolt.org/z/s1h3T6a4E

**Comment by jimblandy** [comment]
Okay, this implements the suggestions from chat.

File: src/proc/index.rs [hunk 1]
```diff
@@ -204,9 +209,7 @@ pub fn find_checked_indexes(
     let mut guarded_indices = BitSet::new();
 
     // Don't bother scanning if we never need `ReadZeroSkipWrite`.
-    if policies.index == BoundsCheckPolicy::ReadZeroSkipWrite
-        || policies.buffer == BoundsCheckPolicy::ReadZeroSkipWrite
-    {
+    if policies.contains(BoundsCheckPolicy::ReadZeroSkipWrite) {
```
Comment (kvark) [inline src/proc/index.rs:212]: this appears to change the semantics a bit, since it includes a case where image policy is `ReadZeroSkipWrite` but index/buffer policies are something different
but I think it's ok, given how niche this scenario is

**Review by kvark — APPROVED** [review]
Sweet!

File: src/proc/index.rs (hunk 1 above)
Comment (jimblandy) [reply src/proc/index.rs:212]: Right, this is not quite needed. But it will be once I have texture bounds checks done.
