### PR TITLE
glsl-out: Perform casts in int only math functions

### LINKED ISSUE #1968: [glsl-out] Invalid GLSL emission when using firstLeadingBit and others
Apologies for the lack of clarity in https://github.com/gfx-rs/naga/issues/1946, but I didn't mention specifically that the GLSL in that issue was emitted by naga after being provided valid WGSL. I assumed it was a glsl-in problem, but it seems I was incorrect - sorry for the confusion! I'm not sure that the GLSL mentioned in the linked issue should be being output by naga, as it's invalid (as answered in the issue).

WGSL:
```
@stage(compute) @workgroup_size(1)
fn main() {
    var var0 = firstLeadingBit(abs(0u));
}
```

GLSL output by naga (included in linked issue, also applies for 450 core):
```
#version 440 core
#extension GL_ARB_compute_shader : require
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

void main() {
    uint var0_ = findMSB(abs(0u));
}
```

Error when validating above GLSL with naga (included in linked issue):
```
error: Unknown function 'findMSB'
  ┌─ temptest.comp:6:18
  │
6 │     uint var0_ = findMSB(abs(0u));
  │                  ^^^^^^^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by JCapucho**
Some functions like abs only accept signed integers while naga's IR
accepts both signed and unsigned integers, this wasn't accounted for in
the glsl backend causing it to produce code that wouldn't type check.

This commit addresses it by performing casts from uint to int of the
function argument and then back from int to uint for the function
return.

closes #1968

~~Edit: found some problems that need to be fixed first~~

Edit2: Good to go now

### CODE REVIEW

**Comment by teoxoy** [comment]
Can we add a test for this?

**Comment by JCapucho** [comment]
> Can we add a test for this?
@teoxoy done

File: src/back/glsl/mod.rs [hunk 1]
```diff
@@ -2798,32 +2798,59 @@ impl<'a, W: Write> Writer<'a, W> {
...
-                                ..
-                            } => {
-                                write!(self.out, "uvec{}(", size as u8)?;
-                                true
-                            }
-                            _ => false,
-                        }
+                // Some GLSL functions always return signed integers (like findMSB),
+                // so they need to be cast to uint if the argument is also an uint.
+                let needs_int_to_uint =
```
Comment (teoxoy) [inline src/back/glsl/mod.rs:2803]: Can we rename this var to something like `ret_needs_int_to_uint`?

File: src/back/glsl/mod.rs [hunk 2]
```diff
@@ -2798,32 +2798,59 @@ impl<'a, W: Write> Writer<'a, W> {
...
+                        kind: crate::ScalarKind::Uint,
+                        size,
+                        ..
+                    } => Some(Some(size)),
+                    _ => None,
                 };
 
+                if let Some(maybe_size) = maybe_uint_size {
+                    // Cast to uint if the function needs it
+                    if needs_int_to_uint {
```
Comment (teoxoy) [inline src/back/glsl/mod.rs:2827]: nit: It might be more self explanatory if we first check `if ret_might_need_int_to_uint` and then do the deconstruction of the option via `if let Some`

File: src/back/glsl/mod.rs [hunk 3]
```diff
@@ -2798,32 +2798,59 @@ impl<'a, W: Write> Writer<'a, W> {
...
+                            None => write!(self.out, "uint(")?,
+                        }
+                    }
+                }
+
                 write!(self.out, "{}(", fun_name)?;
+
+                if let Some(maybe_size) = maybe_uint_size {
+                    // Cast to int if the function needs it
+                    if needs_uint_to_int {
```
Comment (teoxoy) [inline src/back/glsl/mod.rs:2839]: nit: Same as above

**Comment by teoxoy** [comment]
Behavior looks good; just a few things that I think would make the code easier to read.

**Review by jimblandy — CHANGES_REQUESTED** [review]
Just marking this as "changes requested" per @teoxoy's comments, to make it easier to track status.

**Comment by JCapucho** [comment]
Thanks @teoxoy, could you please re-review?

**Review by teoxoy — APPROVED** [review]

**Comment by teoxoy** [comment]
Thanks, @jimblandy; not sure what happened there; I didn't mean to review 4 times 😅

**Review by jimblandy — APPROVED** [review]
