### PR TITLE
wgsl-in: Implement matrix construction from scalar

### LINKED ISSUE #1526: [wgsl-in] Support matrix construction "Column-major construction by elements"
According to the [current WGSL spec](https://gpuweb.github.io/gpuweb/wgsl/#type-constructor-expr), these are valid matrix type constructors:

```wgsl
let foo = mat2x2<f32>(
    1.0, 0.0,
    0.0, 1.0,
);
let bar = mat4x4<f32>(
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, 0.0,
    0.0, 0.0, 0.0, 1.0,
);
```

Copy-pasta from the spec:

| Precondition | Conclusion                              | Notes                                  |
|--------------|-----------------------------------------|----------------------------------------|
|              | `mat2x2<f32>(e1,e2,e3,e4): mat2x2<f32>` |                                        |
|              | `mat3x2<f32>(e1,...,e6): mat3x2<f32>`   |                                        |
|              | `mat2x3<f32>(e1,...,e6): mat2x3<f32>`   |                                        |
| `e1: f32`    | `mat4x2<f32>(e1,...,e8): mat4x2<f32>`   | Column-major construction by elements. |
| `...`        | `mat2x4<f32>(e1,...,e8): mat2x4<f32>`   | `OpCompositeConstruct`                 |
| `eN: f32`    | `mat3x3<f32>(e1,...,e9): mat3x3<f32>`   |                                        |
|              | `mat4x3<f32>(e1,...,e12): mat4x3<f32>`  |                                        |
|              | `mat3x4<f32>(e1,...,e12): mat3x4<f32>`  |                                        |
|              | `mat4x4<f32>(e1,...,e16): mat4x4<f32>`  |                                        |

Current implementation panics:

```
Naga module validation failed: WithSpan { inner: EntryPoint { stage: Vertex, name: "vertex", error: Function(Expression { handle: [17], error: Compose(ComponentCount { given: 16, expected: 4 }) }) }, spans: [(Span { start: 47, end: 178 }, "naga::Expression [17]")] }
```

### PR DESCRIPTION
**Pull request by JCapucho**
Closes #1526

### CODE REVIEW

File: src/front/wgsl/mod.rs [hunk 1]
```diff
@@ -2035,14 +2035,60 @@ impl Parser {
...
+            ) = (
+                ty_resolution.inner_with(ctx.types),
+                ctx.typifier.get(last_component, ctx.types),
+            ) {
+                let vec_ty = ctx.types.insert(
+                    crate::Type {
+                        name: None,
+                        inner: crate::TypeInner::Vector {
+                            width,
+                            kind: crate::ScalarKind::Float,
```
Comment (kvark) [inline src/front/wgsl/mod.rs:2060]: We could just pass `kind` from the `TypeInner::Scalar` to here. Validation will take care of the rest.

**Review by kvark — APPROVED** [review]
