### PR TITLE
[wgsl-in] Add support for the dereference operator

### LINKED ISSUE #1130: [wgsl-in] there is no indirection/dereference operator
The spec [defines](https://gpuweb.github.io/gpuweb/wgsl/#indirection-expr) the familiar syntax `*p` to convert a pointer to a reference, but naga does not support it:

```
fn deref(p: ptr<storage, u32>) {
	let x = *p;
}
```

```
error: expected expression, found '*'
  ┌─ wgsl:2:10
  │
2 │     let x = *p;
  │             ^ expected expression
```

### PR DESCRIPTION
**Pull request by JCapucho**
Closes #1130

### CODE REVIEW

File: src/front/wgsl/mod.rs [hunk 1]
```diff
@@ -2219,6 +2226,7 @@ impl Parser {
         &mut self,
         lexer: &mut Lexer<'a>,
         mut context: ExpressionContext<'a, '_, '_>,
+        rhs: bool,
```
Comment (kvark) [inline src/front/wgsl/mod.rs:2229]: Boolean arguments are an anti-pattern. Let's make this an enum, please?

File: src/front/wgsl/mod.rs [hunk 2]
```diff
@@ -705,9 +709,22 @@ impl<'a> ExpressionContext<'a, '_, '_> {
...
         }
     }
 
+    fn reborrow_rhs(&mut self) -> ExpressionContext<'a, '_, '_> {
+        let mut reborrow = self.reborrow();
+        reborrow.rhs = true;
+        reborrow
+    }
+
+    fn reborrow_lhs(&mut self) -> ExpressionContext<'a, '_, '_> {
```
Comment (kvark) [inline src/front/wgsl/mod.rs:722]: I feel rather strongly that we shouldn't have all 3 of `reborrow()`, `reborrow_rhs()` and `reborrow_lhs()`. First, because the old `reborrow()` becomes rather exceptional. It's almost never that we really want to inherit this flag.
Second, because most of reborrows should be "rhs", so it should be the default.

How do you feel about:
  - `reborrow()` having the RHS semantics. Most of the usage stays unchanged therefore.
  - `reborrow_lhs` having the LHS semantics.
  - `reborrow_lhs_inherit` for inheriting the LHS from the parent, if any

**Review by kvark — COMMENTED** [review]
Eventually, we need to implement "the load rule" as it's spelled in WGSL spec. So basically, we'd keep stuff as a "reference" until a certain point, where we emit the load. Right now, even with your PR, we aren't properly implementing this load rule. For example, passing stuff by pointer into some function wouldn't work correctly.

File: src/front/wgsl/mod.rs (hunk 2 above)
Comment (JCapucho) [reply src/front/wgsl/mod.rs:722]: For me it's fine, I'll change it

Comment (JCapucho) [reply src/front/wgsl/mod.rs:722]: Actually, after trying to implement it I think this adds more confusion and is more error prone for example let's say I have this snippet

```rust
fn test(p: ptr<function, Struct>) {
   (*p).field = 1;
}
```

This is valid wgsl and for it to work in `(*p).field` it starts as lhs trough `parse_singular_expression` it then must go trough `parse_primary_expression` still as lhs, as it's a expression in parentheses it will go trough `parse_general_expression` it then goes trough 2 more calls until reaching `parse_singular_expression` where we finally see the deref, in all of this the lhs must be kept in context, it's more error prone in my opinion to know where it must be inherited than where it must cleared.

**Comment by JCapucho** [comment]
I don't see why it wouldn't work for functions

File: src/front/wgsl/mod.rs (hunk 2 above)
Comment (kvark) [reply src/front/wgsl/mod.rs:722]: there is a a very limited set of things that need to inherit the LHS status, it's precisely the "postfix" things and nothing else.

**Review by kvark — APPROVED** [review]
