### PR TITLE
Fix GLSL output for non-fallthrough switch cases

### LINKED ISSUE #1309: [glsl-out] Switches don't include break
I have this wgsl shader (part of [wgpu_glyph](https://github.com/hecrj/wgpu_glyph/blob/master/src/shader/glyph.wgsl)):
```rs
switch (i32(input)) {
        case 0: {
            
        }
        case 1: {
            
        }
        case 2: {
            
        }
        case 3: {
           
        }
}
```
Before this change: https://github.com/gfx-rs/naga/commit/02c74b50021379092a9d4567fd11aeb0879c5405#diff-cc33bd3c8c18000d3ee7b6f5578e8fa07ffd08d87b0aa3d9525a107937fb3d3f

it used to output this glsl:
```glsl
switch(int(input)) {
            case 0:
                break;
            case 1:
                break;
            case 2:
                break;
            case 3:
                break;
}
```
Now it outputs:
```glsl
switch(int(input)) {
            case 0:

            case 1:

            case 2:

            case 3:
}
```

This breaks wgpu_glyph on OpenGL backend. ~~I'm not sure if this is correct behavior for wgsl, does it brake by default? Judging by other backend, I always thought so.~~

### PR DESCRIPTION
**Pull request by hcsch**
Fixes #1309 by partially reverting 02c74b50021379092a9d4567fd11aeb0879c5405.
Also cleans up the GLSL output by only inserting a `break` where a case is not already broken out of at the end of the case body and inserts a comment indicating explicitly fallthrough cases.

Also adds a test case for switch statements not in the last statement position of a function, because those might have return statements inserted, which previously might have made it harder to notice some missing `break`s that should have been inserted.

### CODE REVIEW

File: src/back/glsl/mod.rs [hunk 1]
```diff
@@ -1441,6 +1441,21 @@ impl<'a, W: Write> Writer<'a, W> {
...
                     }
+
+                    // Write fallthrough comment if the case is fallthrough,
+                    // otherwise write a break, if the case is not already
+                    // broken out of at the end of its body.
+                    if case.fall_through {
+                        writeln!(self.out, "{}/* fallthrough */", INDENT.repeat(indent + 2))?;
+                    } else if !matches!(
+                        case.body.last(),
+                        Some(&Statement::Break)
```
Comment (kvark) [inline src/back/glsl/mod.rs:1452]: we should probably add a helper method here so that this looks like `statement.is_jump()` or something similar

**Review by kvark — APPROVED** [review]
Nice, thank you!

**Comment by PolyMeilex** [comment]
Thank you!

File: src/back/glsl/mod.rs (hunk 1 above)
Comment (hcsch) [reply src/back/glsl/mod.rs:1452]: I was considering adding something like that, but I wasn't very sure about what to call it and whether this one use would justify the addition. Since this PR is merged already, should I do a follow up PR for this?

**Comment by kvark** [comment]
Published in 0.6.2
