### PR TITLE
[glsl-in] add support for .length()

### LINKED ISSUE #2016: [glsl-in] naga rejects .length() unconditionally
minimal example:
```glsl
#version 440 core

layout(std430, binding = 0) buffer something_buf {
    uint something[];
};

void main() {
    uint test = uint(something.length());
}
```

naga-cli rejects this with the following error
```
error: Expected Comma or RightParen, found LeftParen
  ┌─ minimal.comp:8:38
  │
8 │     uint test = uint(something.length());
  │                                      ^
```

### PR DESCRIPTION
**Pull request by SpaceCat-Chan**
this fixes #2016

i see two reasons you may not want to merge this
1. this assumes that .length() is only valid on arrays and never has any other meaning
2. this assumes that .length() has the same semantics as `Expression::ArrayLength`, which it may not have

other than that there should be no problems, other than that this was done in a hasty way

### CODE REVIEW

**Comment by JCapucho** [comment]
> this fixes #2016

thank you for working on this

> i see two reasons you may not want to merge this
> 
>     1. this assumes that .length() is only valid on arrays and never has any other meaning

According to the glsl specification this should be the case

>     2. this assumes that .length() has the same semantics as `Expression::ArrayLength`, which it may not have

There's a slight difference, `Expression::ArrayLength` follows wgsl semantics as almost all of naga's IR follows, in wgsl `arrayLength` returns a `u32` which is glsl's `uint`, meanwhile `.length()` should return a `int` so you need to add a cast.

> other than that there should be no problems, other than that this was done in a hasty way

I do have another issue with the current implementation, it specializes the parsing on `.length()` which is the only method on the base glsl specification, but I don't know if there any extensions that add other methods or might appear new extensions that do so, so I think we should parse a `HirExprKind::Method` and then handle this in lowering, this also has the added benefit that error messages can be better instead of `no such field`

**Comment by SpaceCat-Chan** [comment]
latest commit adds a cast to Sint, and makes the parsing parse any method and then only specializes on .length in lowering instead

**Review by JCapucho — CHANGES_REQUESTED** [review]
Amazing work, I wasn't expecting you to include argument handling but nice that you added it.

There are some issues that need to be addressed and I also added some nits.

Also please add a test (you can add it to `expressions.frag`)

**Review by JCapucho — COMMENTED** [review]
Amazing work, but I noticed while testing your changes that `ArrayLength` only works on pointer to dynamic arrays, while glsl expects `.length` to work on all arrays.

To fix this we would need to check the type of the expression and if it's an array of fixed size or a pointer to it pass it as a constant.

File: src/front/glsl/context.rs [hunk 1]
```diff
@@ -1366,6 +1366,64 @@ impl Context {
...
+                                    ".length() doesn't take any arguments".into(),
+                                ),
+                                meta,
+                            });
+                        }
+                        let lowered_array =
+                            self.lower_expect_inner(stmt, parser, object, pos, body)?.0;
+                        let array_type = parser.resolve_type(self, lowered_array, meta)?;
+                        match array_type {
+                            &TypeInner::Array {
```
Comment (JCapucho) [inline src/front/glsl/context.rs]: Prefer de referencing the match expression 
```suggestion
                        match *array_type {
                            TypeInner::Array {
```

File: src/front/glsl/context.rs [hunk 2]
```diff
@@ -1366,6 +1366,64 @@ impl Context {
...
+                                base: _,
+                                size: crate::ArraySize::Constant(size),
+                                stride: _,
```
Comment (JCapucho) [inline src/front/glsl/context.rs]: Prefer using ellipsis `..`
```suggestion
                                size: crate::ArraySize::Constant(size),
                                ..
```

File: src/front/glsl/context.rs [hunk 3]
```diff
@@ -1366,6 +1366,64 @@ impl Context {
...
+                            } => {
+                                let mut array_length = self.add_expression(
+                                    Expression::Constant(size),
+                                    stmt.hir_exprs[expr].meta,
+                                    body,
+                                );
+                                self.conversion(&mut array_length, meta, ScalarKind::Sint, 4)?;
```
Comment (JCapucho) [inline src/front/glsl/context.rs]: Use `forced_conversion` in this case because constant array sizes might already be `Sint`
```suggestion
                                self.forced_conversion(&mut array_length, meta, ScalarKind::Sint, 4)?;
```

File: tests/in/glsl/expressions.frag [hunk 4]
```diff
@@ -132,6 +132,14 @@ void testMatrixMultiplication(mat4x3 a, mat4x4 b) {
...
 }
 
+layout(std430, binding = 0) buffer a_buf {
+    float a[];
+};
+
+void testLength() {
+    int len = a.length();
+}
+
```
Comment (JCapucho) [inline tests/in/glsl/expressions.frag:142]: Let's add another test for arrays with constant size
```suggestion

void testConstantLength(float a[4u]) {
    int len = a.length();
}

```

**Review by JCapucho — CHANGES_REQUESTED** [review]
Almost perfect just left some nits and ask that you add a test for constant size arrays.

**Comment by JCapucho** [comment]
Sorry I might have misled you but since we are already lowering with a non `Lhs` context we don't need to check if the array is wrapped in a pointer.

File: src/front/glsl/context.rs [hunk 5]
```diff
@@ -1366,6 +1366,73 @@ impl Context {
...
+                                    meta,
+                                    body,
+                                );
+                                self.forced_conversion(
+                                    parser,
+                                    &mut array_length,
+                                    meta,
+                                    ScalarKind::Sint,
+                                    4,
+                                )?;
```
Comment (JCapucho) [inline src/front/glsl/context.rs:1421]: I only meant the previous branch, in here we can be sure it will be an `Uint` and a cast will be neeeded

**Review by JCapucho — CHANGES_REQUESTED** [review]

**Review by JCapucho — APPROVED** [review]
Perfect, thanks for your contribution.
