### PR TITLE
glsl-in: Fix matrix multiplication check

### LINKED ISSUE #1947: [glsl] Translating matrix multiplication from WGSL->GLSL and validating throws error
Translating the following piece of WGSL code to GLSL 440 or 450 using naga returns no errors, but validating the translated .comp shader with naga throws an error.

WGSL (works for any matrices being multiplied that are not both square):
```
@stage(compute) @workgroup_size(1)
fn main() {
	var var0 = mat4x3<f32>() * mat4x4<f32>();
}
```

Error:
```
        error: Cannot apply operation to Matrix { columns: Quad, rows: Tri, width: 4 } and Matrix { columns: Quad, rows: Quad, width: 4 }
          ┌─ temp_output.comp:8:14
          │
        8 │     var0_ = (mat4x3(vec3(0.0, 0.0, 0.0), vec3(0.0, 0.0, 0.0), vec3(0.0, 0.0, 0.0), vec3(0.0, 0.0, 0.0)) * mat4x4(vec4(0.0, 0.0, 0.0, 0.0), vec4(0.0, 0.0, 0.0, 0.0), vec4(0.0, 0.0, 0.0, 0.0), vec4(0.0, 0.0, 0.0, 0.0)));
          │              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        

```

Translated GLSL from glsl-out:
```
#version 430 core
#extension GL_ARB_compute_shader : require
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;


void main() {
    mat4x3 var0_ = mat4x3(0.0);
    var0_ = (mat4x3(vec3(0.0, 0.0, 0.0), vec3(0.0, 0.0, 0.0), vec3(0.0, 0.0, 0.0), vec3(0.0, 0.0, 0.0)) * mat4x4(vec4(0.0, 0.0, 0.0, 0.0), vec4(0.0, 0.0, 0.0, 0.0), vec4(0.0, 0.0, 0.0, 0.0), vec4(0.0, 0.0, 0.0, 0.0)));
    return;
}
```

### PR DESCRIPTION
**Pull request by JCapucho**
The previous check compared rows to rows and columns to columns but
multiplication of matrices only needs the columns of the left matrix to
be equal to the rows of the right matrix.

closes #1947

### CODE REVIEW

File: src/front/glsl/context.rs [hunk 1]
```diff
@@ -617,9 +617,13 @@ impl Context {
                             width: right_width,
                         },
                     ) => {
+                        let additive_check =
+                            left_columns != right_columns || left_rows != right_rows;
+                        let multiplicative_check = left_columns != right_rows;
+
```
Comment (jimblandy) [inline src/front/glsl/context.rs:623]: Suggest:

```
                        let dimensions_ok = if op == BinaryOperator::Multiply {
                            left_columns == right_rows
                        } else {
                            left_columns == right_columns && left_rows == right_rows
                        };

                        // Check that the two arguments have the same dimensions
                        if !dimensions_ok || left_width != right_width {
```

**Review by jimblandy — APPROVED** [review]
Thank you!

One suggestion:
