### PR TITLE
Fix `Expression::Load` generating

### LINKED ISSUE #910: Statements are incorrectly ordered from `mtl` and `glsl` backends.
I've created a gist with steps to reproduce [here](https://gist.github.com/paulgb/a8f705d9e80bbfd0ca42410086a5c04f).

The input WGSL code is:

    [...snip; full code in linked repo]
    var a: f32 = 0.0;
    let b: f32 = a;
    a = 1.0;
    v_data.data = b;
    [snip...]

The correct resulting value of `v_data.data` is `0.0`.

The code returned by `naga` for `metal` is:

    [snip]
    float a = 0.0;
    a = 1.0;
    v_data.data = a;
    return;
    [snip...]

The resulting value of `v_data.data` is `1.0`. The value `b` is written out entirely, but instead of taking on the value at the time of its assignment, it takes on the value of `a` at the end.

The `.spv` file itself appears to be ordered correctly, so the issue appears to occur between loading the `.spv` file and generating the output in the backend. To confirm this, I used `spirv-cross` to generate metal and glsl output from the same input `.spv` returned by `naga`; these files are correctly ordered.

I'm planning to keep digging into this, but I wanted to raise it as an issue in case it's come up elsewhere.

In case anyone needs a workaround, changing `let` expressions to `var` expressions seems to fix it, possibly with a small performance penalty.

### PR DESCRIPTION
**Pull request by Gordon-F**
One more attempt to fix #910. Also added this case as a snapshot.

Previous discussion in #914.

### CODE REVIEW

File: src/back/mod.rs [hunk 1]
```diff
@@ -20,16 +20,24 @@ impl crate::Expression {
...
+    fn bake_ref_count(&self, expressions: &crate::Arena<crate::Expression>) -> usize {
+        const OTHER_EXPR_BAKE_COUNT: usize = 2;
         match *self {
             // accesses are never cached, only loads are
             crate::Expression::Access { .. } | crate::Expression::AccessIndex { .. } => !0,
             // sampling may use the control flow, and image ops look better by themselves
             crate::Expression::ImageSample { .. } | crate::Expression::ImageLoad { .. } => 1,
             // derivatives use the control flow
             crate::Expression::Derivative { .. } => 1,
+            crate::Expression::Load { pointer } => match expressions[pointer] {
```
Comment (kvark) [inline src/back/mod.rs:32]: This is not a complete fix, right? The expression can also be an access into something that is a variable, or it can be a global variable. In all the cases we want to load early.
So technically, returning `1` here is the only good solution. Why are we not doing this?

**Review by kvark — CHANGES_REQUESTED** [review]

File: src/back/mod.rs (hunk 1 above)
Comment (Gordon-F) [reply src/back/mod.rs:32]: It's a temporary solution. We can safely add Global Variable here without any validation error. I will try to investigate how we can fix glsl array and named expression on wgsl frontend side.

Comment (kvark) [reply src/back/mod.rs:32]: What about `Access` and `AccessIndex`?

I'm not sure how you are seeing this being addressed on WGSL frontend. This seems like a backend issue.

**Comment by Gordon-F** [comment]
Ok, I guess I should fix #851 first.

**Comment by Gordon-F** [comment]
@kvark CI is happy now.

File: src/back/glsl/mod.rs [hunk 2]
```diff
@@ -521,7 +521,11 @@ impl<'a, W: Write> Writer<'a, W> {
                 // glsl has no concept of samplers so we just ignore it
                 TypeInner::Sampler { .. } => continue,
                 // All other globals are written by `write_global`
-                _ => self.write_global(handle, global)?,
+                _ => {
+                    let end_with_newline =
+                        index != self.module.global_variables.len().saturating_sub(1);
```
Comment (kvark) [inline src/back/glsl/mod.rs:526]: This isn't going to work, since we are skipping the unused globals anyway. So your item may end up being the last in the list.

File: src/back/glsl/mod.rs [hunk 3]
```diff
@@ -769,6 +774,10 @@ impl<'a, W: Write> Writer<'a, W> {
         };
         writeln!(self.out, ";")?;
 
+        if add_a_newline {
```
Comment (kvark) [inline src/back/glsl/mod.rs:777]: seems a bit weird to add this extra parameter and bit of logic, given that it can be done outside of this function. Is this to re-use it better?

File: src/back/mod.rs (hunk 1 above)
Comment (kvark) [reply src/back/mod.rs:32]: Wouldn't it be simpler to just return 1 here without checking the actual expressions? I don't understand what this gives us.

File: tests/in/baked-load.wgsl [hunk 4]
```diff
@@ -0,0 +1,16 @@
+[[block]]
+struct IOData {
```
Comment (kvark) [inline tests/in/baked-load.wgsl:2]: would it be possible to merge this into `access.wgsl`?

**Comment by JCapucho** [comment]
If i may ask why do you want to add a newline between globals in `glsl-out` and why do you check if it's the last global to write a newline just writing always a newline would in the worst case add two newlines and even then I don't think it will because you need to write the varyings

**Comment by Gordon-F** [comment]
@kvark, @JCapucho Thank you! All suggestions addressed. I hope we will find a way how we can avoid unnecessary code generation.
