### PR TITLE
[glsl-out] Fix bitcast operation for the same types

### LINKED ISSUE #1131: Cannot bitcast Uint to  Uint
Using wgpu 0.9, without "cross" feature enabled I get this:
```
[2021-07-23T13:41:37Z INFO  naga::front::spv] Patching...
[2021-07-23T13:41:37Z INFO  gfx_backend_gl::device]     Compiled shader 5
[2021-07-23T13:41:37Z WARN  gfx_backend_gl::device] Naga GLSL write: Cannot bitcast Uint to Uint
[2021-07-23T13:41:37Z WARN  wgpu::backend::direct] Shader translation error for stage FRAGMENT: Shader module failed to compile: Custom("Cannot bitcast Uint to Uint") shader compilation failed: Fragment
[2021-07-23T13:41:37Z WARN  wgpu::backend::direct] Please report it to https://github.com/gfx-rs/naga
[2021-07-23T13:41:37Z WARN  wgpu::backend::direct] Try enabling `wgpu/cross` feature as a workaround.
[2021-07-23T13:41:37Z ERROR wgpu::backend::direct] wgpu error: Validation Error

    Caused by:
        In Device::create_render_pipeline
        Internal error in FRAGMENT shader: Shader module failed to compile: Custom("Cannot bitcast Uint to Uint") shader compilation failed: Fragment

```

Include the following shader parts to reproduce:
```
/*---------------------------------------------------------------
 * Random
 *---------------------------------------------------------------*/
// Modified from: iq's "Integer Hash - III" (https://www.shadertoy.com/view/4tXyWN)
// Faster than "full" xxHash and good quality

uint base_hash(uvec2 p)
{
    uvec2 q = 1103515245U * ((p >> 1U) ^ (p.yx));
    uint  n = 1103515245U * ((q.x) ^ (q.y >> 3U));
    return n ^ (n >> 16);
}

float hash1(uvec2 x)
{
    uint n = base_hash(x);
    return float(n) * (1.0 / float(0xffffffffU));
}

vec2 hash2(uvec2 x)
{
    uint n = base_hash(x);
    uvec2 rz = uvec2(n, n * 48271U);
    return vec2((rz.xy >> 1) & uvec2(0x7fffffffU)) / float(0x7fffffff);
}

vec3 hash3(uvec2 x)
{
    uint n = base_hash(x);
    uvec3 rz = uvec3(n, n * 16807U, n * 48271U);
    return vec3((rz >> 1) & uvec3(0x7fffffffU)) / float(0x7fffffff);
}

uvec2 rseed = uvec2(gl_FragCoord.x, base_hash(uvec2(gl_FragCoord.xy)));

float hash1() { return hash1(floatBitsToUint(uvec2(rseed.x += 1, rseed.y += 1))); }
vec2  hash2() { return hash2(floatBitsToUint(uvec2(rseed.x += 1, rseed.y += 1))); }
vec3  hash3() { return hash3(floatBitsToUint(uvec2(rseed.x += 1, rseed.y += 1))); }

vec3 random_sphere_direction()
{
    vec2 h = hash2() * vec2(2.0, 6.28318530718) - vec2(1.0, 0.0);
    float phi = h.y;
    return vec3(sqrt(1.0 - h.x * h.x) * vec2(sin(phi), cos(phi)), h.x);
}

vec3 random_hemisphere_direction(vec3 n)
{
    vec3 dr = random_sphere_direction();
    return dot(dr, n) * dr;
}

vec3 random_cos_weighted_hemisphere_direction(vec3 n)
{
    vec2 r = hash2();

    vec3  uu = normalize(cross(n, vec3(0.0, 1.0, 1.0)));
    vec3  vv = cross(uu, n);

    float ra = sqrt(r.y);
    float rx = ra * cos(6.2831 * r.x);
    float ry = ra * sin(6.2831 * r.x);
    float rz = sqrt(1.0 - r.y);
    vec3  rr = vec3(rx*uu + ry*vv + rz*n);

    return normalize(rr);
}
```

### PR DESCRIPTION
**Pull request by Gordon-F**
That's strange, but we don't have any tests for this case 🤔 

Fix #1131.

### CODE REVIEW

File: src/back/glsl/mod.rs [hunk 1]
```diff
@@ -2252,36 +2252,51 @@ impl<'a, W: Write> Writer<'a, W> {
...
-                                // There is no way to bitcast between Uint/Sint in glsl. Use constructor conversion
-                                (Sk::Uint, Sk::Sint) => "int",
-                                (Sk::Sint, Sk::Uint) => "uint",
-                                _ => {
-                                    return Err(Error::Custom(format!(
-                                        "Cannot bitcast {:?} to {:?}",
-                                        source_kind, target_kind
-                                    )));
-                                }
+                        let (conv_op, need_parentheses) = match (source_kind, target_kind) {
```
Comment (kvark) [inline src/back/glsl/mod.rs:2264]: the `need_parentheses` seems redundant, we could just check `conv_op.is_empty()`

**Review by kvark — COMMENTED** [review]
Would be great to add tests here. I think a separate test file, like `convert.wgsl` could check the paths for conversions, bitcasts, and packing instructions in the future.

**Comment by Gordon-F** [comment]
`Cannot bitcast` error was removed from code.

**Review by kvark — APPROVED** [review]
