### PR TITLE
[wgsl-in] Handle all(bool) and any(bool)

### LINKED ISSUE #1911: [wgsl-in] Error on provision of boolean scalars to all/any built-in functions
The specification provides two overloads for the `all` and `any` built-in functions, with one accepting boolean vectors and the second accepting boolean scalars. naga appears to only accept the former.

code example (analogous for `any`):
```
@compute @workgroup_size(1)
fn compute_main() {
	var var0 = all(true);
}
```

naga compilation error:
```
[2022-05-11T18:19:19Z ERROR naga::valid::expression] All/Any of type Scalar { kind: Bool, width: 1 }
error: 
  ┌─ all_any_scalar.wgsl:3:12
  │
3 │     var var0 = all(true);
  │               ^^^^^^^^^^ naga::Expression [2]

Entry point compute_main at Compute is invalid: 
	Expression [2] is invalid
	Relational argument [1] is not a boolean vector
```

### PR DESCRIPTION
**Pull request by fornwall**
In wgsl there are overloads for `all(bool)` and `any(bool)` which just returns the boolean unmodified.

As at least glsl [any](https://registry.khronos.org/OpenGL-Refpages/gl4/html/any.xhtml) and [all](https://registry.khronos.org/OpenGL-Refpages/gl4/html/all.xhtml) does not support that, let's remove them while lowering to get rid of them early.

Fixes #1911.

### CODE REVIEW

**Comment by fornwall** [comment]
The build failure is #2447.

File: src/front/wgsl/lower/mod.rs [hunk 1]
```diff
@@ -1696,7 +1696,20 @@ impl<'source, 'temp> Lowerer<'source, 'temp> {
...
                     args.finish()?;
 
-                    crate::Expression::Relational { fun, argument }
+                    // Check for no-op all(bool) and any(bool):
+                    let argument_unmodified = matches!(
+                        fun,
+                        crate::RelationalFunction::All | crate::RelationalFunction::Any
+                    ) && {
+                        ctx.grow_types(argument)?;
+                        matches!(ctx.resolved_inner(argument), &crate::TypeInner::Scalar { kind, .. } if kind == crate::ScalarKind::Bool)
```
Comment (teoxoy) [inline src/front/wgsl/lower/mod.rs:1705]:
```suggestion
                        matches!(ctx.resolved_inner(argument), &crate::TypeInner::Scalar { kind: crate::ScalarKind::Bool, .. })
```

**Review by teoxoy — APPROVED** [review]
Besides the suggestion, LGTM; I think it makes sense for this no-op to be handled by the frontend.

File: src/front/wgsl/lower/mod.rs (hunk 1 above)
Comment (fornwall) [reply src/front/wgsl/lower/mod.rs]: Thanks!

**Comment by fornwall** [comment]
> Besides the suggestion, LGTM; I think it makes sense for this no-op to be handled by the frontend.

Thanks - applied the suggestion and squashed the commits.
