### PR TITLE
Validate built-ins to not repeat

### LINKED ISSUE #888: Using position from vertex output and frag coord causes panic on metal
Shader example:
```
struct VertexOutput {
    [[builtin(position)]] position: vec4<f32>;
};

[[stage(vertex)]]
fn vs_main() -> VertexOutput {
    var out: VertexOutput;
    out.position = vec4<f32>(0.0, 0.0, 0.0, 0.0);
    return out;
}

[[stage(fragment)]]
fn fs_main(
    input: VertexOutput,
    [[builtin(position)]] coord: vec4<f32>
) -> [[location(0)]] vec4<f32> {
    return vec4<f32>(0.0, 0.0, 0.0, 0.0);
}
```

The error:

```
wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `iced_wgpu::quad pipeline`
    Internal error in VERTEX shader: Error compiling the shader "\"Compilation failed: \\n\\nprogram_source:106:17: error: declaration with attribute \\\'position\\\' already specified\\n, metal::float4 coord [[position]]\\n  ~~~~~~~~~~~~~~^~~~~\\nprogram_source:105:17: note: previous declaration with attribute \\\'position\\\' here\\n, metal::float4 position [[position]]\\n                ^\\n\""
```

 I do not get this on windows/vulkan. Logically it makes sense to me, but I don't know how this is normally handled in metal and can't find an example online. Is it allowed to have [[stage_in]] that defines position and then also a [[position]] frag coord as a parameter? If not, is there a way I can annotate this for it to understand better?

Note, I don't have a mac so I assume the top shader should produce the error, but it was from a report so I can't test it.

### PR DESCRIPTION
**Pull request by kvark**
Fixes #888

### CODE REVIEW

File: src/valid/mod.rs [hunk 1]
```diff
@@ -94,6 +94,7 @@ pub struct Validator {
     types: Vec<r#type::TypeInfo>,
     layouter: Layouter,
     location_mask: BitSet,
+    built_ins: FastHashSet<crate::BuiltIn>,
```
Comment (jimblandy) [inline src/valid/mod.rs:97]: Suggestion: we could probably just use a `BitSet` here, just as we do for `location_mask`, and cast `BuiltIn` to `usize` when we work with it. (The C programmer in me wants a `u32`, but that's not the way we do things any more...)

**Review by jimblandy — APPROVED** [review]
Looks good to me.

File: src/valid/mod.rs (hunk 1 above)
Comment (kvark) [reply src/valid/mod.rs:97]: oh indeed, I'll do this
